// AUTO GENERATED checklist content (40 tasks). Edit gen_checklist_data.py to change.
export type ChLang = "en" | "ru" | "de" | "it" | "es" | "zh" | "pt" | "hi" | "fr";
type L = Record<ChLang, string>;
export interface ChTask { c: number; h: number; name: L; }
export interface ChChrome { kicker: string; h1: string; intro: string; catsIntro: string; reclaimLabel: string; daysLabel: string; daysUnit: string; tickHint: string; share: string; copied: string; resultKicker: string; cta: string; ctaNote: string; accioLabel: string; ctaLine: string; note: string; metaTitle: string; metaDesc: string; }
export const chChrome: Record<ChLang, ChChrome> = {
  "en": {
    "kicker": "Free interactive checklist",
    "h1": "40 tasks you can hand to an AI agent this week",
    "intro": "Tick the tasks you would gladly stop doing yourself. As you go, we add up the hours an AI agent could reclaim each month. No sign-up to use it.",
    "catsIntro": "Six areas, forty tasks. Pick what eats your time.",
    "reclaimLabel": "Hours reclaimed a month",
    "daysLabel": "That is roughly",
    "daysUnit": "working days a year",
    "tickHint": "Tick what you would delegate",
    "share": "Share my result",
    "copied": "Link copied",
    "resultKicker": "Hours an AI agent could reclaim",
    "cta": "Delegate these to Accio Work",
    "ctaNote": "Free plan, no card required",
    "accioLabel": "Ready to hand them off",
    "ctaLine": "Accio Work runs these tasks end to end on live Alibaba data, browser included, and waits for your approval on anything that matters.",
    "note": "Time estimates are rough averages for a small business, not a promise. Your numbers depend on your workload.",
    "metaTitle": "40 tasks you can hand to an AI agent | Accio Work",
    "metaDesc": "Free interactive checklist: tick the work you would delegate and see the hours an AI agent could reclaim each month. Nine languages."
  },
  "ru": {
    "kicker": "Бесплатный интерактивный чеклист",
    "h1": "40 задач, которые можно отдать AI-агенту уже на этой неделе",
    "intro": "Отметьте задачи, которые с радостью перестали бы делать сами. По ходу мы складываем часы, которые AI-агент может отвоёвывать каждый месяц. Регистрация не нужна.",
    "catsIntro": "Шесть областей, сорок задач. Выберите то, что съедает ваше время.",
    "reclaimLabel": "Отвоёванных часов в месяц",
    "daysLabel": "Это примерно",
    "daysUnit": "рабочих дней в год",
    "tickHint": "Отметьте, что делегировали бы",
    "share": "Поделиться результатом",
    "copied": "Ссылка скопирована",
    "resultKicker": "Часы, которые может отвоевать AI-агент",
    "cta": "Отдать это Accio Work",
    "ctaNote": "Бесплатный план, карта не нужна",
    "accioLabel": "Готовы отдать",
    "ctaLine": "Accio Work выполняет эти задачи от начала до конца на живых данных Alibaba, включая браузер, и ждёт вашего одобрения на всём важном.",
    "note": "Оценки времени это грубые средние для малого бизнеса, не обещание. Ваши цифры зависят от вашей нагрузки.",
    "metaTitle": "40 задач, которые можно отдать AI-агенту | Accio Work",
    "metaDesc": "Бесплатный интерактивный чеклист: отметьте работу, которую делегировали бы, и увидите, сколько часов в месяц отвоюет AI-агент. 9 языков."
  },
  "de": {
    "kicker": "Kostenlose interaktive Checkliste",
    "h1": "40 Aufgaben, die du diese Woche an einen AI-Agenten abgeben kannst",
    "intro": "Hake die Aufgaben ab, die du gern loswerden würdest. Unterwegs zählen wir die Stunden, die ein AI-Agent monatlich zurückholen könnte. Ohne Anmeldung nutzbar.",
    "catsIntro": "Sechs Bereiche, vierzig Aufgaben. Wähle, was deine Zeit frisst.",
    "reclaimLabel": "Zurückgewonnene Stunden pro Monat",
    "daysLabel": "Das sind etwa",
    "daysUnit": "Arbeitstage pro Jahr",
    "tickHint": "Hake ab, was du abgeben würdest",
    "share": "Mein Ergebnis teilen",
    "copied": "Link kopiert",
    "resultKicker": "Stunden, die ein AI-Agent zurückholen könnte",
    "cta": "An Accio Work abgeben",
    "ctaNote": "Kostenloser Plan, keine Karte nötig",
    "accioLabel": "Bereit abzugeben",
    "ctaLine": "Accio Work erledigt diese Aufgaben von Anfang bis Ende auf Live-Alibaba-Daten, Browser inklusive, und wartet bei allem Wichtigen auf deine Freigabe.",
    "note": "Zeitschätzungen sind grobe Mittelwerte für ein kleines Unternehmen, kein Versprechen. Deine Zahlen hängen von deiner Last ab.",
    "metaTitle": "40 Aufgaben für einen AI-Agenten | Accio Work",
    "metaDesc": "Kostenlose interaktive Checkliste: hake ab, was du abgeben würdest, und sieh die Stunden, die ein AI-Agent pro Monat zurückholt. Neun Sprachen."
  },
  "it": {
    "kicker": "Checklist interattiva gratuita",
    "h1": "40 attività che puoi affidare a un agente AI questa settimana",
    "intro": "Spunta le attività che smetteresti volentieri di fare. Man mano sommiamo le ore che un agente AI potrebbe recuperare ogni mese. Nessuna registrazione per usarla.",
    "catsIntro": "Sei aree, quaranta attività. Scegli ciò che ti mangia il tempo.",
    "reclaimLabel": "Ore recuperate al mese",
    "daysLabel": "Sono circa",
    "daysUnit": "giorni lavorativi l'anno",
    "tickHint": "Spunta ciò che delegheresti",
    "share": "Condividi il risultato",
    "copied": "Link copiato",
    "resultKicker": "Ore che un agente AI potrebbe recuperare",
    "cta": "Affidale ad Accio Work",
    "ctaNote": "Piano gratuito, nessuna carta",
    "accioLabel": "Pronto a delegarle",
    "ctaLine": "Accio Work esegue queste attività dall'inizio alla fine su dati Alibaba in tempo reale, browser incluso, e attende la tua approvazione su ciò che conta.",
    "note": "Le stime di tempo sono medie approssimative per una piccola impresa, non una promessa. I tuoi numeri dipendono dal tuo carico.",
    "metaTitle": "40 attività da affidare a un agente AI | Accio Work",
    "metaDesc": "Checklist interattiva gratuita: spunta il lavoro che delegheresti e vedi le ore che un agente AI recupera ogni mese. Nove lingue."
  },
  "es": {
    "kicker": "Checklist interactiva gratis",
    "h1": "40 tareas que puedes delegar a un agente de IA esta semana",
    "intro": "Marca las tareas que con gusto dejarías de hacer. Sobre la marcha sumamos las horas que un agente de IA podría recuperar cada mes. Sin registro para usarla.",
    "catsIntro": "Seis áreas, cuarenta tareas. Elige lo que se come tu tiempo.",
    "reclaimLabel": "Horas recuperadas al mes",
    "daysLabel": "Son unos",
    "daysUnit": "días laborables al año",
    "tickHint": "Marca lo que delegarías",
    "share": "Compartir mi resultado",
    "copied": "Enlace copiado",
    "resultKicker": "Horas que un agente de IA podría recuperar",
    "cta": "Delegarlas a Accio Work",
    "ctaNote": "Plan gratuito, sin tarjeta",
    "accioLabel": "Listo para delegar",
    "ctaLine": "Accio Work ejecuta estas tareas de principio a fin con datos de Alibaba en vivo, navegador incluido, y espera tu aprobación en lo que importa.",
    "note": "Las estimaciones de tiempo son promedios aproximados para una pyme, no una promesa. Tus cifras dependen de tu carga.",
    "metaTitle": "40 tareas para delegar a un agente de IA | Accio Work",
    "metaDesc": "Checklist interactiva gratis: marca el trabajo que delegarías y ve las horas que un agente de IA recupera cada mes. Nueve idiomas."
  },
  "zh": {
    "kicker": "免费互动清单",
    "h1": "本周就能交给 AI 智能体的 40 项任务",
    "intro": "勾选你乐意不再亲手做的任务。随着勾选，我们累计 AI 智能体每月可为你省下的工时。无需注册即可使用。",
    "catsIntro": "六个领域，四十项任务。挑出吃掉你时间的那些。",
    "reclaimLabel": "每月省下的工时",
    "daysLabel": "大约相当于",
    "daysUnit": "个工作日每年",
    "tickHint": "勾选你会外包的",
    "share": "分享我的结果",
    "copied": "链接已复制",
    "resultKicker": "AI 智能体可省下的工时",
    "cta": "把这些交给 Accio Work",
    "ctaNote": "免费方案，无需绑卡",
    "accioLabel": "准备好交出去",
    "ctaLine": "Accio Work 基于阿里实时数据端到端执行这些任务，含浏览器操作，重要环节等你确认。",
    "note": "时间估算是小企业的粗略平均值，并非承诺。你的数字取决于你的工作量。",
    "metaTitle": "可交给 AI 智能体的 40 项任务 | Accio Work",
    "metaDesc": "免费互动清单：勾选你会外包的工作，看看 AI 智能体每月能省下多少工时。九种语言。"
  },
  "pt": {
    "kicker": "Checklist interativa grátis",
    "h1": "40 tarefas que você pode delegar a um agente de IA esta semana",
    "intro": "Marque as tarefas que você deixaria de fazer com prazer. Ao marcar, somamos as horas que um agente de IA poderia recuperar por mês. Sem cadastro para usar.",
    "catsIntro": "Seis áreas, quarenta tarefas. Escolha o que come o seu tempo.",
    "reclaimLabel": "Horas recuperadas por mês",
    "daysLabel": "São cerca de",
    "daysUnit": "dias úteis por ano",
    "tickHint": "Marque o que delegaria",
    "share": "Compartilhar meu resultado",
    "copied": "Link copiado",
    "resultKicker": "Horas que um agente de IA poderia recuperar",
    "cta": "Delegar ao Accio Work",
    "ctaNote": "Plano gratuito, sem cartão",
    "accioLabel": "Pronto para delegar",
    "ctaLine": "O Accio Work executa essas tarefas de ponta a ponta em dados ao vivo da Alibaba, navegador incluído, e espera sua aprovação no que importa.",
    "note": "As estimativas de tempo são médias aproximadas para uma pequena empresa, não uma promessa. Seus números dependem da sua carga.",
    "metaTitle": "40 tarefas para delegar a um agente de IA | Accio Work",
    "metaDesc": "Checklist interativa grátis: marque o trabalho que delegaria e veja as horas que um agente de IA recupera por mês. Nove idiomas."
  },
  "hi": {
    "kicker": "मुफ्त इंटरैक्टिव चेकलिस्ट",
    "h1": "इस हफ्ते AI एजेंट को सौंपने लायक 40 काम",
    "intro": "वे काम चुनें जो आप खुशी-खुशी खुद करना छोड़ देंगे। साथ-साथ हम जोड़ते हैं कि AI एजेंट हर महीने कितने घंटे बचा सकता है। इस्तेमाल के लिए साइन-अप नहीं चाहिए।",
    "catsIntro": "छह क्षेत्र, चालीस काम। वही चुनें जो आपका समय खा जाते हैं।",
    "reclaimLabel": "हर महीने बचे घंटे",
    "daysLabel": "यह लगभग",
    "daysUnit": "कार्यदिवस प्रति वर्ष",
    "tickHint": "जो सौंपेंगे उसे चुनें",
    "share": "मेरा परिणाम शेयर करें",
    "copied": "लिंक कॉपी हो गया",
    "resultKicker": "AI एजेंट जितने घंटे बचा सकता है",
    "cta": "ये Accio Work को सौंपें",
    "ctaNote": "मुफ्त प्लान, कार्ड की जरूरत नहीं",
    "accioLabel": "सौंपने को तैयार",
    "ctaLine": "Accio Work इन कामों को अलीबाबा के लाइव डेटा पर शुरू से अंत तक करता है, ब्राउज़र समेत, और हर अहम कदम पर आपकी मंजूरी का इंतज़ार करता है।",
    "note": "समय अनुमान छोटे व्यवसाय के लिए मोटे औसत हैं, वादा नहीं। आपके आंकड़े आपके काम के बोझ पर निर्भर हैं।",
    "metaTitle": "AI एजेंट को सौंपने लायक 40 काम | Accio Work",
    "metaDesc": "मुफ्त इंटरैक्टिव चेकलिस्ट: जो काम सौंपेंगे उन्हें चुनें और देखें कि AI एजेंट हर महीने कितने घंटे बचा सकता है। नौ भाषाएं।"
  },
  "fr": {
    "kicker": "Checklist interactive gratuite",
    "h1": "40 tâches à confier à un agent IA cette semaine",
    "intro": "Cochez les tâches que vous arrêteriez volontiers de faire vous-même. Au fil des clics, nous additionnons les heures qu'un agent IA pourrait récupérer chaque mois. Sans inscription.",
    "catsIntro": "Six domaines, quarante tâches. Choisissez ce qui dévore votre temps.",
    "reclaimLabel": "Heures récupérées par mois",
    "daysLabel": "Cela fait environ",
    "daysUnit": "jours ouvrés par an",
    "tickHint": "Cochez ce que vous délégueriez",
    "share": "Partager mon résultat",
    "copied": "Lien copié",
    "resultKicker": "Heures qu'un agent IA pourrait récupérer",
    "cta": "Déléguer à Accio Work",
    "ctaNote": "Offre gratuite, sans carte",
    "accioLabel": "Prêt à déléguer",
    "ctaLine": "Accio Work exécute ces tâches de bout en bout sur des données Alibaba en direct, navigateur inclus, et attend votre validation sur l'essentiel.",
    "note": "Les estimations de temps sont des moyennes approximatives pour une petite entreprise, pas une promesse. Vos chiffres dépendent de votre charge.",
    "metaTitle": "40 tâches à confier à un agent IA | Accio Work",
    "metaDesc": "Checklist interactive gratuite : cochez le travail que vous délégueriez et voyez les heures qu'un agent IA récupère chaque mois. Neuf langues."
  }
};

export const chCats: { name: L }[] = [{"name": {"en": "Sourcing and suppliers", "ru": "Сорсинг и поставщики", "de": "Sourcing und Lieferanten", "it": "Sourcing e fornitori", "es": "Sourcing y proveedores", "zh": "选品与供应商", "pt": "Sourcing e fornecedores", "hi": "सोर्सिंग और सप्लायर", "fr": "Sourcing et fournisseurs"}}, {"name": {"en": "Store and e-commerce ops", "ru": "Магазин и операции e-commerce", "de": "Store und E-Commerce-Betrieb", "it": "Negozio e operazioni e-commerce", "es": "Tienda y operaciones e-commerce", "zh": "店铺与电商运营", "pt": "Loja e operações de e-commerce", "hi": "स्टोर और ई-कॉमर्स ऑप्स", "fr": "Boutique et opérations e-commerce"}}, {"name": {"en": "Marketing and content", "ru": "Маркетинг и контент", "de": "Marketing und Content", "it": "Marketing e contenuti", "es": "Marketing y contenido", "zh": "营销与内容", "pt": "Marketing e conteúdo", "hi": "मार्केटिंग और कंटेंट", "fr": "Marketing et contenu"}}, {"name": {"en": "Research and market data", "ru": "Ресёрч и данные рынка", "de": "Recherche und Marktdaten", "it": "Ricerca e dati di mercato", "es": "Investigación y datos de mercado", "zh": "调研与市场数据", "pt": "Pesquisa e dados de mercado", "hi": "रिसर्च और बाज़ार डेटा", "fr": "Recherche et données marché"}}, {"name": {"en": "Operations and admin", "ru": "Операции и админ", "de": "Betrieb und Admin", "it": "Operazioni e admin", "es": "Operaciones y admin", "zh": "运营与行政", "pt": "Operações e admin", "hi": "संचालन और एडमिन", "fr": "Opérations et admin"}}, {"name": {"en": "Automation and custom tools", "ru": "Автоматизация и свои инструменты", "de": "Automatisierung und eigene Tools", "it": "Automazione e strumenti su misura", "es": "Automatización y herramientas propias", "zh": "自动化与定制工具", "pt": "Automação e ferramentas próprias", "hi": "ऑटोमेशन और कस्टम टूल", "fr": "Automatisation et outils sur mesure"}}];

export const chTasks: ChTask[] = [{"c": 0, "h": 5, "name": {"en": "Find verified suppliers for a new product", "ru": "Найти проверенных поставщиков под новый товар", "de": "Geprüfte Lieferanten für ein neues Produkt finden", "it": "Trovare fornitori verificati per un nuovo prodotto", "es": "Encontrar proveedores verificados para un producto nuevo", "zh": "为新品找到已核验供应商", "pt": "Encontrar fornecedores verificados para um novo produto", "hi": "नए प्रोडक्ट के लिए सत्यापित सप्लायर खोजें", "fr": "Trouver des fournisseurs vérifiés pour un nouveau produit"}}, {"c": 0, "h": 2.5, "name": {"en": "Send first-contact inquiries", "ru": "Отправить первичные запросы поставщикам", "de": "Erstkontakt-Anfragen senden", "it": "Inviare le prime richieste di contatto", "es": "Enviar consultas de primer contacto", "zh": "发送首次询盘", "pt": "Enviar consultas de primeiro contato", "hi": "पहला संपर्क पूछताछ भेजें", "fr": "Envoyer les premières prises de contact"}}, {"c": 0, "h": 6, "name": {"en": "Negotiate price and terms by email", "ru": "Вести переговоры о цене и условиях по почте", "de": "Preis und Konditionen per E-Mail verhandeln", "it": "Negoziare prezzo e condizioni via email", "es": "Negociar precio y condiciones por email", "zh": "邮件谈价格与条款", "pt": "Negociar preço e condições por email", "hi": "ईमेल से कीमत और शर्तें तय करें", "fr": "Négocier prix et conditions par email"}}, {"c": 0, "h": 1.5, "name": {"en": "Compare supplier quotes side by side", "ru": "Сравнить предложения поставщиков рядом", "de": "Lieferantenangebote nebeneinander vergleichen", "it": "Confrontare i preventivi dei fornitori", "es": "Comparar cotizaciones de proveedores", "zh": "并排比较供应商报价", "pt": "Comparar cotações de fornecedores lado a lado", "hi": "सप्लायर कोट्स की तुलना करें", "fr": "Comparer les devis fournisseurs côte à côte"}}, {"c": 0, "h": 1.5, "name": {"en": "Background-check a supplier", "ru": "Проверить поставщика на надёжность", "de": "Einen Lieferanten prüfen", "it": "Verificare un fornitore", "es": "Verificar los antecedentes de un proveedor", "zh": "背调供应商", "pt": "Verificar o histórico de um fornecedor", "hi": "सप्लायर की पृष्ठभूमि जाँचें", "fr": "Vérifier les antécédents d'un fournisseur"}}, {"c": 0, "h": 1.5, "name": {"en": "Chase unanswered RFQs", "ru": "Дожать поставщиков без ответа", "de": "Unbeantwortete Anfragen nachfassen", "it": "Sollecitare le richieste senza risposta", "es": "Perseguir cotizaciones sin respuesta", "zh": "催促无回复的询盘", "pt": "Cobrar cotações sem resposta", "hi": "बिना जवाब वाले RFQ पर फॉलो-अप", "fr": "Relancer les demandes sans réponse"}}, {"c": 0, "h": 2, "name": {"en": "Look up duties and market-entry rules", "ru": "Проверить пошлины и правила ввоза", "de": "Zölle und Marktzutrittsregeln prüfen", "it": "Verificare dazi e regole di ingresso", "es": "Consultar aranceles y reglas de entrada", "zh": "查关税与入市规则", "pt": "Consultar impostos e regras de entrada", "hi": "शुल्क और बाज़ार-प्रवेश नियम देखें", "fr": "Vérifier droits et règles d'accès au marché"}}, {"c": 0, "h": 1.5, "name": {"en": "Monitor raw-material and component prices", "ru": "Отслеживать цены на сырьё и комплектующие", "de": "Rohstoff- und Komponentenpreise beobachten", "it": "Monitorare i prezzi di materie prime e componenti", "es": "Vigilar precios de materias primas y componentes", "zh": "监控原料与元件价格", "pt": "Monitorar preços de matéria-prima e componentes", "hi": "कच्चे माल और पुर्जों के दाम पर नज़र", "fr": "Suivre les prix des matières et composants"}}, {"c": 1, "h": 14, "name": {"en": "Spin up a store from a product idea", "ru": "Собрать магазин из идеи товара", "de": "Aus einer Produktidee einen Store aufbauen", "it": "Creare un negozio da un'idea di prodotto", "es": "Montar una tienda desde una idea de producto", "zh": "从一个点子搭起店铺", "pt": "Montar uma loja a partir de uma ideia", "hi": "आइडिया से स्टोर तैयार करें", "fr": "Créer une boutique à partir d'une idée"}}, {"c": 1, "h": 4, "name": {"en": "Write product descriptions in bulk", "ru": "Написать описания товаров массово", "de": "Produktbeschreibungen in Masse schreiben", "it": "Scrivere descrizioni prodotto in blocco", "es": "Escribir descripciones de producto en masa", "zh": "批量写商品描述", "pt": "Escrever descrições de produto em massa", "hi": "बल्क में प्रोडक्ट विवरण लिखें", "fr": "Rédiger des fiches produit en masse"}}, {"c": 1, "h": 2, "name": {"en": "Optimize titles and meta for search", "ru": "Оптимизировать заголовки и мету под поиск", "de": "Titel und Meta für die Suche optimieren", "it": "Ottimizzare titoli e meta per la ricerca", "es": "Optimizar títulos y meta para búsqueda", "zh": "为搜索优化标题与元信息", "pt": "Otimizar títulos e meta para busca", "hi": "सर्च के लिए टाइटल और मेटा सुधारें", "fr": "Optimiser titres et méta pour la recherche"}}, {"c": 1, "h": 1.5, "name": {"en": "Track competitor prices and restocks", "ru": "Отслеживать цены и поставки конкурентов", "de": "Wettbewerberpreise und Nachschub verfolgen", "it": "Monitorare prezzi e riassortimenti dei concorrenti", "es": "Seguir precios y reposiciones de competidores", "zh": "跟踪竞品价格与补货", "pt": "Acompanhar preços e reposições dos concorrentes", "hi": "प्रतियोगी के दाम और रीस्टॉक ट्रैक करें", "fr": "Suivre prix et réassorts des concurrents"}}, {"c": 1, "h": 1, "name": {"en": "Send a weekly sales summary", "ru": "Присылать недельную сводку продаж", "de": "Wöchentliche Verkaufsübersicht senden", "it": "Inviare un riepilogo vendite settimanale", "es": "Enviar un resumen de ventas semanal", "zh": "每周发送销售汇总", "pt": "Enviar um resumo de vendas semanal", "hi": "साप्ताहिक बिक्री सारांश भेजें", "fr": "Envoyer un résumé des ventes hebdo"}}, {"c": 1, "h": 1.5, "name": {"en": "Turn product reviews into a fix-list", "ru": "Превратить отзывы в список правок", "de": "Produktbewertungen in eine To-do-Liste verwandeln", "it": "Trasformare le recensioni in una lista di fix", "es": "Convertir reseñas en una lista de mejoras", "zh": "把评价变成改进清单", "pt": "Transformar avaliações em lista de correções", "hi": "रिव्यू को सुधार-सूची में बदलें", "fr": "Transformer les avis en liste de correctifs"}}, {"c": 2, "h": 2.5, "name": {"en": "Build a 30-day content calendar", "ru": "Составить контент-план на 30 дней", "de": "30-Tage-Content-Kalender erstellen", "it": "Creare un calendario contenuti di 30 giorni", "es": "Crear un calendario de contenido de 30 días", "zh": "做一份 30 天内容日历", "pt": "Montar um calendário de conteúdo de 30 dias", "hi": "30 दिन का कंटेंट कैलेंडर बनाएं", "fr": "Bâtir un calendrier de contenu sur 30 jours"}}, {"c": 2, "h": 3, "name": {"en": "Draft social posts in your voice", "ru": "Писать посты в вашем стиле", "de": "Social-Posts in deiner Stimme entwerfen", "it": "Scrivere post social nel tuo tono", "es": "Redactar posts en tu voz", "zh": "用你的口吻起草社媒帖子", "pt": "Redigir posts na sua voz", "hi": "आपकी शैली में सोशल पोस्ट लिखें", "fr": "Rédiger des posts dans votre ton"}}, {"c": 2, "h": 4.5, "name": {"en": "Write and build a landing page", "ru": "Написать и собрать лендинг", "de": "Landingpage schreiben und bauen", "it": "Scrivere e costruire una landing", "es": "Escribir y montar una landing", "zh": "撰写并搭建落地页", "pt": "Escrever e montar uma landing", "hi": "लैंडिंग पेज लिखें और बनाएं", "fr": "Rédiger et construire une landing"}}, {"c": 2, "h": 1.5, "name": {"en": "Produce ad-copy variants to test", "ru": "Сделать варианты рекламных текстов", "de": "Anzeigentexte zum Testen erstellen", "it": "Creare varianti di copy per i test", "es": "Crear variantes de copy para testear", "zh": "做广告文案变体供测试", "pt": "Criar variações de copy para testar", "hi": "टेस्ट के लिए विज्ञापन कॉपी वेरिएंट", "fr": "Créer des variantes d'accroche à tester"}}, {"c": 2, "h": 2, "name": {"en": "Draft and schedule the newsletter", "ru": "Готовить и планировать рассылку", "de": "Newsletter entwerfen und planen", "it": "Scrivere e programmare la newsletter", "es": "Redactar y programar el newsletter", "zh": "起草并排期邮件通讯", "pt": "Redigir e agendar a newsletter", "hi": "न्यूज़लेटर लिखें और शेड्यूल करें", "fr": "Rédiger et planifier la newsletter"}}, {"c": 2, "h": 1.5, "name": {"en": "Repurpose one post into ten", "ru": "Из одного поста сделать десять", "de": "Aus einem Post zehn machen", "it": "Da un post ricavarne dieci", "es": "Convertir un post en diez", "zh": "一条内容拆成十条", "pt": "De um post fazer dez", "hi": "एक पोस्ट से दस बनाएं", "fr": "D'un post en faire dix"}}, {"c": 2, "h": 2, "name": {"en": "Research keywords and hashtags", "ru": "Исследовать ключи и хэштеги", "de": "Keywords und Hashtags recherchieren", "it": "Ricerca di keyword e hashtag", "es": "Investigar keywords y hashtags", "zh": "调研关键词与话题标签", "pt": "Pesquisar palavras-chave e hashtags", "hi": "कीवर्ड और हैशटैग रिसर्च", "fr": "Rechercher mots-clés et hashtags"}}, {"c": 3, "h": 4.5, "name": {"en": "Run niche and market research", "ru": "Провести ресёрч ниши и рынка", "de": "Nischen- und Marktrecherche durchführen", "it": "Fare ricerca di nicchia e mercato", "es": "Investigar nicho y mercado", "zh": "做细分与市场调研", "pt": "Pesquisar nicho e mercado", "hi": "नीश और बाज़ार रिसर्च करें", "fr": "Mener une étude de niche et marché"}}, {"c": 3, "h": 1.5, "name": {"en": "Get a weekly competitor digest", "ru": "Получать недельный дайджест конкурентов", "de": "Wöchentlichen Wettbewerber-Digest erhalten", "it": "Ricevere un digest settimanale dei concorrenti", "es": "Recibir un resumen semanal de competidores", "zh": "获取每周竞品动态摘要", "pt": "Receber um resumo semanal de concorrentes", "hi": "साप्ताहिक प्रतियोगी डाइजेस्ट पाएं", "fr": "Recevoir un digest concurrents hebdo"}}, {"c": 3, "h": 1.5, "name": {"en": "Audit your site SEO on schedule", "ru": "Проверять SEO сайта по расписанию", "de": "Website-SEO nach Zeitplan prüfen", "it": "Fare l'audit SEO del sito su pianificazione", "es": "Auditar el SEO del sitio en agenda", "zh": "定时审计站点 SEO", "pt": "Auditar o SEO do site no cronograma", "hi": "शेड्यूल पर साइट SEO ऑडिट", "fr": "Auditer le SEO du site à intervalle"}}, {"c": 3, "h": 0.75, "name": {"en": "Research a buyer before a call", "ru": "Изучить клиента перед звонком", "de": "Einen Kunden vor dem Call recherchieren", "it": "Studiare un cliente prima di una call", "es": "Investigar a un comprador antes de una llamada", "zh": "通话前研究买家", "pt": "Pesquisar um comprador antes da call", "hi": "कॉल से पहले खरीदार को रिसर्च करें", "fr": "Se renseigner sur un prospect avant un appel"}}, {"c": 3, "h": 0.75, "name": {"en": "Read a morning market briefing", "ru": "Читать утренний обзор рынка", "de": "Ein Morgens-Markt-Briefing lesen", "it": "Leggere un briefing di mercato mattutino", "es": "Leer un briefing de mercado matinal", "zh": "读一份早间市场简报", "pt": "Ler um briefing de mercado matinal", "hi": "सुबह का मार्केट ब्रीफ पढ़ें", "fr": "Lire un brief de marché matinal"}}, {"c": 3, "h": 2.5, "name": {"en": "Monitor social and forums for your brand", "ru": "Мониторить соцсети и форумы по бренду", "de": "Social und Foren nach deiner Marke beobachten", "it": "Monitorare social e forum per il tuo brand", "es": "Monitorear redes y foros de tu marca", "zh": "监控社媒与论坛的品牌提及", "pt": "Monitorar redes e fóruns sobre sua marca", "hi": "अपने ब्रांड के लिए सोशल और फोरम मॉनिटर करें", "fr": "Surveiller réseaux et forums pour votre marque"}}, {"c": 4, "h": 4, "name": {"en": "Triage your inbox", "ru": "Разбирать входящую почту", "de": "Deinen Posteingang sortieren", "it": "Gestire la posta in arrivo", "es": "Ordenar tu bandeja de entrada", "zh": "收件箱分拣", "pt": "Triar sua caixa de entrada", "hi": "अपना इनबॉक्स छाँटें", "fr": "Trier votre boîte de réception"}}, {"c": 4, "h": 0.75, "name": {"en": "Turn meeting notes into action items", "ru": "Из заметок встречи сделать задачи", "de": "Meeting-Notizen in Aufgaben verwandeln", "it": "Trasformare le note in azioni", "es": "Convertir notas de reunión en tareas", "zh": "把会议记录变成待办", "pt": "Transformar notas em ações", "hi": "मीटिंग नोट्स को टास्क बनाएं", "fr": "Transformer les notes de réunion en actions"}}, {"c": 4, "h": 2.5, "name": {"en": "Keep the CRM updated", "ru": "Держать CRM в актуальном виде", "de": "Das CRM aktuell halten", "it": "Tenere aggiornato il CRM", "es": "Mantener el CRM actualizado", "zh": "保持 CRM 更新", "pt": "Manter o CRM atualizado", "hi": "CRM अपडेट रखें", "fr": "Tenir le CRM à jour"}}, {"c": 4, "h": 1, "name": {"en": "Prepare the weekly numbers report", "ru": "Готовить недельный отчёт по цифрам", "de": "Den wöchentlichen Zahlenreport erstellen", "it": "Preparare il report settimanale dei numeri", "es": "Preparar el informe semanal de números", "zh": "准备每周数据报告", "pt": "Preparar o relatório semanal de números", "hi": "साप्ताहिक आंकड़ों की रिपोर्ट बनाएं", "fr": "Préparer le rapport chiffré hebdo"}}, {"c": 4, "h": 2, "name": {"en": "Process files and clean data", "ru": "Обрабатывать файлы и чистить данные", "de": "Dateien verarbeiten und Daten bereinigen", "it": "Elaborare file e pulire dati", "es": "Procesar archivos y limpiar datos", "zh": "处理文件并清洗数据", "pt": "Processar arquivos e limpar dados", "hi": "फाइलें प्रोसेस करें और डेटा साफ करें", "fr": "Traiter des fichiers et nettoyer des données"}}, {"c": 4, "h": 1, "name": {"en": "Run price checks on your own SKUs", "ru": "Проверять цены по своим SKU", "de": "Preisprüfungen für eigene SKUs laufen lassen", "it": "Controllare i prezzi dei tuoi SKU", "es": "Revisar precios de tus propios SKU", "zh": "检查自家 SKU 价格", "pt": "Checar preços dos seus SKUs", "hi": "अपने SKU के दाम जाँचें", "fr": "Vérifier les prix de vos SKU"}}, {"c": 4, "h": 2, "name": {"en": "Draft routine replies", "ru": "Готовить типовые ответы", "de": "Routineantworten entwerfen", "it": "Scrivere risposte di routine", "es": "Redactar respuestas rutinarias", "zh": "起草常规回复", "pt": "Redigir respostas de rotina", "hi": "रूटीन जवाब तैयार करें", "fr": "Rédiger les réponses courantes"}}, {"c": 5, "h": 1.5, "name": {"en": "Set up automations that run while you sleep", "ru": "Настроить автоматизации, что работают ночью", "de": "Automatisierungen einrichten, die nachts laufen", "it": "Impostare automazioni che girano di notte", "es": "Configurar automatizaciones que corren de noche", "zh": "设置夜间自动运行的流程", "pt": "Configurar automações que rodam à noite", "hi": "रात में चलने वाले ऑटोमेशन सेट करें", "fr": "Mettre en place des automatisations nocturnes"}}, {"c": 5, "h": 3, "name": {"en": "Get a custom tool built on the spot", "ru": "Получить свой инструмент на месте", "de": "Ein eigenes Tool auf Anhieb bauen lassen", "it": "Farsi costruire uno strumento su misura", "es": "Conseguir una herramienta a medida al momento", "zh": "当场做出一个定制工具", "pt": "Ter uma ferramenta sob medida na hora", "hi": "मौके पर कस्टम टूल बनवाएं", "fr": "Obtenir un outil sur mesure sur le champ"}}, {"c": 5, "h": 2, "name": {"en": "Automate LinkedIn follow-ups", "ru": "Автоматизировать фоллоу-апы в LinkedIn", "de": "LinkedIn-Follow-ups automatisieren", "it": "Automatizzare i follow-up su LinkedIn", "es": "Automatizar seguimientos en LinkedIn", "zh": "自动化 LinkedIn 跟进", "pt": "Automatizar follow-ups no LinkedIn", "hi": "LinkedIn फॉलो-अप ऑटोमेट करें", "fr": "Automatiser les relances LinkedIn"}}, {"c": 5, "h": 1, "name": {"en": "Run a team of specialist agents", "ru": "Запустить команду агентов-специалистов", "de": "Ein Team von Spezialagenten betreiben", "it": "Gestire un team di agenti specialisti", "es": "Ejecutar un equipo de agentes especialistas", "zh": "运行一队专职智能体", "pt": "Rodar uma equipe de agentes especialistas", "hi": "विशेषज्ञ एजेंटों की टीम चलाएं", "fr": "Faire tourner une équipe d'agents spécialisés"}}, {"c": 5, "h": 3, "name": {"en": "Delegate browser work", "ru": "Отдать работу в браузере", "de": "Browserarbeit delegieren", "it": "Delegare il lavoro nel browser", "es": "Delegar el trabajo en el navegador", "zh": "把浏览器操作交出去", "pt": "Delegar o trabalho no navegador", "hi": "ब्राउज़र का काम सौंपें", "fr": "Déléguer le travail dans le navigateur"}}, {"c": 5, "h": 0.5, "name": {"en": "Ship work with one approval", "ru": "Отправлять работу одним одобрением", "de": "Arbeit mit einer Freigabe ausliefern", "it": "Pubblicare con una sola approvazione", "es": "Publicar con una sola aprobación", "zh": "一次确认即可交付", "pt": "Publicar com uma única aprovação", "hi": "एक मंजूरी से काम भेजें", "fr": "Livrer avec une seule validation"}}];
