// AUTO GENERATED duty content. Edit gen_duty_data.py to change.
export type DutyLang = "en" | "ru" | "de" | "it" | "es" | "zh" | "pt" | "hi" | "fr";
export interface DutyChrome { kicker: string; h1: string; intro: string; productCost: string; units: string; shipping: string; dutyRate: string; dutyHint: string; importTax: string; importHint: string; sellPrice: string; destination: string; dutyAmount: string; importAmount: string; landedUnit: string; landedTotal: string; marginUnit: string; marginPct: string; vHealthyT: string; vHealthyB: string; vTightT: string; vTightB: string; vUnderT: string; vUnderB: string; vNoneT: string; vNoneB: string; disclaimer: string; ctaLine: string; cta: string; ctaNote: string; dUS: string; dEU: string; dUK: string; metaTitle: string; metaDesc: string; }
export const dutyChrome: Record<DutyLang, DutyChrome> = {
  "en": {
    "kicker": "Updated for 2026",
    "h1": "Duty and landed cost calculator",
    "intro": "The $800 de minimis exemption is gone, so most cross border parcels now owe duty and clear customs. Enter your numbers to see your true cost per unit and whether selling parcel by parcel still pays.",
    "productCost": "Product cost per unit",
    "units": "Units in this order",
    "shipping": "Shipping and freight (total)",
    "dutyRate": "Duty and tariff rate",
    "dutyHint": "Enter your product rate from its HTS code. China origin goods have faced high stacked tariffs since 2025.",
    "importTax": "Import VAT or handling",
    "importHint": "Rough default by market. Edit to your case.",
    "sellPrice": "Your sell price per unit (optional)",
    "destination": "Destination market",
    "dutyAmount": "Estimated duty",
    "importAmount": "Import VAT and fees",
    "landedUnit": "Landed cost per unit",
    "landedTotal": "Total landed cost",
    "marginUnit": "Margin per unit",
    "marginPct": "Margin",
    "vHealthyT": "Margins hold",
    "vHealthyB": "At this landed cost you keep a workable margin. Keep an eye on duty rate changes and shipping.",
    "vTightT": "Margins are tight",
    "vTightB": "Duty and fees eat most of your margin. Bulk importing to a local warehouse can cut per parcel duty and handling.",
    "vUnderT": "Underwater on this model",
    "vUnderB": "At this landed cost the per parcel route loses money. Bulk import, or sourcing from another origin, may be the only way to make it work.",
    "vNoneT": "Your landed cost",
    "vNoneB": "Add a sell price above to see your margin and a verdict.",
    "disclaimer": "Estimates only. Actual duty depends on exact HTS classification, origin and current policy, which changes often. This is not customs or tax advice. Confirm with a licensed customs broker.",
    "ctaLine": "Accio Work sources across origins and handles VAT filings and customs documentation in 100+ markets.",
    "cta": "Start free on Accio Work",
    "ctaNote": "Free plan, no card required",
    "dUS": "United States",
    "dEU": "European Union",
    "dUK": "United Kingdom",
    "metaTitle": "Duty and landed cost calculator after de minimis | Accio Work",
    "metaDesc": "Free calculator for import duty, VAT and true landed cost per unit after the end of the $800 de minimis exemption. See if per parcel selling still pays."
  },
  "ru": {
    "kicker": "Актуально 2026",
    "h1": "Калькулятор пошлин и реальной себестоимости",
    "intro": "Освобождение $800 (de minimis) отменено, теперь большинство трансграничных посылок облагается пошлиной и проходит таможню. Введите свои цифры и узнайте реальную себестоимость за единицу и выгодно ли ещё продавать по одной посылке.",
    "productCost": "Цена товара за единицу",
    "units": "Единиц в заказе",
    "shipping": "Доставка и фрахт (всего)",
    "dutyRate": "Ставка пошлины и тарифа",
    "dutyHint": "Введите ставку для вашего товара по коду HTS. Товары из Китая с 2025 попадают под высокие суммарные тарифы.",
    "importTax": "Импортный VAT или сборы",
    "importHint": "Примерное значение по рынку. Подставьте своё.",
    "sellPrice": "Ваша цена продажи за единицу (необязательно)",
    "destination": "Рынок назначения",
    "dutyAmount": "Оценка пошлины",
    "importAmount": "Импортный VAT и сборы",
    "landedUnit": "Себестоимость за единицу",
    "landedTotal": "Полная себестоимость",
    "marginUnit": "Маржа за единицу",
    "marginPct": "Маржа",
    "vHealthyT": "Маржа держится",
    "vHealthyB": "При такой себестоимости остаётся рабочая маржа. Следите за изменением ставок и стоимости доставки.",
    "vTightT": "Маржа на грани",
    "vTightB": "Пошлина и сборы съедают почти всю маржу. Опт на локальный склад снижает пошлину и обработку на единицу.",
    "vUnderT": "Модель в минусе",
    "vUnderB": "При такой себестоимости продажа по одной посылке убыточна. Помочь может опт или смена страны происхождения.",
    "vNoneT": "Ваша себестоимость",
    "vNoneB": "Укажите цену продажи выше, чтобы увидеть маржу и вердикт.",
    "disclaimer": "Только оценка. Реальная пошлина зависит от точной классификации HTS, страны происхождения и текущей политики, которая часто меняется. Это не таможенная и не налоговая консультация. Уточняйте у лицензированного брокера.",
    "ctaLine": "Accio Work ищет поставщиков по разным странам и ведёт VAT-отчётность и таможенные документы в 100+ рынках.",
    "cta": "Начать бесплатно в Accio Work",
    "ctaNote": "Бесплатный план, карта не нужна",
    "dUS": "США",
    "dEU": "Евросоюз",
    "dUK": "Великобритания",
    "metaTitle": "Калькулятор пошлин и себестоимости после de minimis | Accio Work",
    "metaDesc": "Бесплатный расчёт импортной пошлины, VAT и реальной себестоимости за единицу после отмены освобождения $800. Узнайте, выгодно ли продавать по одной посылке."
  },
  "de": {
    "kicker": "Aktuell 2026",
    "h1": "Zoll- und Landed-Cost-Rechner",
    "intro": "Die 800-Dollar-De-minimis-Befreiung ist weg, die meisten grenzüberschreitenden Pakete zahlen jetzt Zoll und müssen durch den Zoll. Gib deine Zahlen ein und sieh deine echten Stückkosten und ob Verkauf Paket für Paket noch lohnt.",
    "productCost": "Produktkosten pro Stück",
    "units": "Stück in dieser Bestellung",
    "shipping": "Versand und Fracht (gesamt)",
    "dutyRate": "Zoll- und Tarifsatz",
    "dutyHint": "Gib den Satz deines Produkts nach HTS-Code ein. Waren aus China unterliegen seit 2025 hohen gestapelten Tarifen.",
    "importTax": "Einfuhr-USt oder Gebühren",
    "importHint": "Grober Marktwert. An deinen Fall anpassen.",
    "sellPrice": "Dein Verkaufspreis pro Stück (optional)",
    "destination": "Zielmarkt",
    "dutyAmount": "Geschätzter Zoll",
    "importAmount": "Einfuhr-USt und Gebühren",
    "landedUnit": "Landed Cost pro Stück",
    "landedTotal": "Gesamte Landed Cost",
    "marginUnit": "Marge pro Stück",
    "marginPct": "Marge",
    "vHealthyT": "Marge hält",
    "vHealthyB": "Bei diesen Kosten bleibt eine tragfähige Marge. Achte auf Änderungen bei Zollsätzen und Versand.",
    "vTightT": "Marge ist knapp",
    "vTightB": "Zoll und Gebühren fressen fast die ganze Marge. Ein Import in Menge in ein lokales Lager senkt Zoll und Handling pro Stück.",
    "vUnderT": "Modell im Minus",
    "vUnderB": "Bei diesen Kosten verliert der Weg Paket für Paket Geld. Mengenimport oder ein anderes Ursprungsland kann helfen.",
    "vNoneT": "Deine Landed Cost",
    "vNoneB": "Gib oben einen Verkaufspreis ein, um Marge und Urteil zu sehen.",
    "disclaimer": "Nur Schätzung. Der echte Zoll hängt von exakter HTS-Klassifizierung, Ursprung und aktueller Politik ab, die sich oft ändert. Keine Zoll- oder Steuerberatung. Kläre es mit einem lizenzierten Zollbroker.",
    "ctaLine": "Accio Work beschafft aus verschiedenen Ländern und übernimmt USt-Meldungen und Zolldokumente in 100+ Märkten.",
    "cta": "Kostenlos mit Accio Work starten",
    "ctaNote": "Kostenloser Plan, keine Karte nötig",
    "dUS": "USA",
    "dEU": "Europäische Union",
    "dUK": "Vereinigtes Königreich",
    "metaTitle": "Zoll- und Landed-Cost-Rechner nach De minimis | Accio Work",
    "metaDesc": "Kostenloser Rechner für Einfuhrzoll, USt und echte Landed Cost pro Stück nach dem Ende der 800-Dollar-De-minimis-Befreiung. Lohnt sich Verkauf pro Paket noch?"
  },
  "it": {
    "kicker": "Aggiornato 2026",
    "h1": "Calcolatore di dazi e costo a destino",
    "intro": "L'esenzione de minimis da 800 dollari non c'è più, quindi la maggior parte dei pacchi transfrontalieri ora paga dazio e passa la dogana. Inserisci i tuoi numeri per vedere il costo reale per unità e se vendere pacco per pacco conviene ancora.",
    "productCost": "Costo prodotto per unità",
    "units": "Unità in questo ordine",
    "shipping": "Spedizione e trasporto (totale)",
    "dutyRate": "Aliquota dazio e tariffa",
    "dutyHint": "Inserisci l'aliquota del tuo prodotto dal codice HTS. I beni di origine cinese subiscono alte tariffe cumulate dal 2025.",
    "importTax": "IVA import o gestione",
    "importHint": "Valore indicativo per mercato. Adattalo al tuo caso.",
    "sellPrice": "Il tuo prezzo di vendita per unità (facoltativo)",
    "destination": "Mercato di destinazione",
    "dutyAmount": "Dazio stimato",
    "importAmount": "IVA import e spese",
    "landedUnit": "Costo a destino per unità",
    "landedTotal": "Costo a destino totale",
    "marginUnit": "Margine per unità",
    "marginPct": "Margine",
    "vHealthyT": "Il margine tiene",
    "vHealthyB": "A questo costo resta un margine utile. Tieni d'occhio i cambi di aliquota e la spedizione.",
    "vTightT": "Margine risicato",
    "vTightB": "Dazio e spese mangiano quasi tutto il margine. Importare in blocco in un magazzino locale riduce dazio e gestione per unità.",
    "vUnderT": "Modello in perdita",
    "vUnderB": "A questo costo la via pacco per pacco perde soldi. Import in blocco o un'altra origine possono essere l'unica strada.",
    "vNoneT": "Il tuo costo a destino",
    "vNoneB": "Aggiungi un prezzo di vendita sopra per vedere margine e verdetto.",
    "disclaimer": "Solo stime. Il dazio reale dipende dalla classificazione HTS esatta, dall'origine e dalla politica attuale, che cambia spesso. Non è consulenza doganale o fiscale. Verifica con un doganalista autorizzato.",
    "ctaLine": "Accio Work si rifornisce da più origini e gestisce dichiarazioni IVA e documenti doganali in oltre 100 mercati.",
    "cta": "Inizia gratis su Accio Work",
    "ctaNote": "Piano gratuito, nessuna carta richiesta",
    "dUS": "Stati Uniti",
    "dEU": "Unione Europea",
    "dUK": "Regno Unito",
    "metaTitle": "Calcolatore di dazi e costo a destino dopo de minimis | Accio Work",
    "metaDesc": "Calcolatore gratuito per dazio, IVA e costo a destino reale per unità dopo la fine dell'esenzione de minimis da 800 dollari."
  },
  "es": {
    "kicker": "Actualizado 2026",
    "h1": "Calculadora de aranceles y costo total",
    "intro": "La exención de minimis de 800 dólares ya no existe, así que la mayoría de los paquetes transfronterizos ahora pagan arancel y pasan aduana. Introduce tus cifras para ver tu costo real por unidad y si vender paquete a paquete sigue saliendo a cuenta.",
    "productCost": "Costo del producto por unidad",
    "units": "Unidades en este pedido",
    "shipping": "Envío y flete (total)",
    "dutyRate": "Tasa de arancel y tarifa",
    "dutyHint": "Introduce la tasa de tu producto según su código HTS. Los bienes de origen chino enfrentan altos aranceles acumulados desde 2025.",
    "importTax": "IVA de importación o gestión",
    "importHint": "Valor orientativo por mercado. Ajústalo a tu caso.",
    "sellPrice": "Tu precio de venta por unidad (opcional)",
    "destination": "Mercado de destino",
    "dutyAmount": "Arancel estimado",
    "importAmount": "IVA de importación y tasas",
    "landedUnit": "Costo total por unidad",
    "landedTotal": "Costo total a destino",
    "marginUnit": "Margen por unidad",
    "marginPct": "Margen",
    "vHealthyT": "El margen aguanta",
    "vHealthyB": "A este costo te queda un margen viable. Vigila los cambios de arancel y el envío.",
    "vTightT": "Margen ajustado",
    "vTightB": "El arancel y las tasas se comen casi todo el margen. Importar a granel a un almacén local reduce arancel y gestión por unidad.",
    "vUnderT": "Modelo en pérdidas",
    "vUnderB": "A este costo la vía paquete a paquete pierde dinero. Importar a granel u otra origen pueden ser la única salida.",
    "vNoneT": "Tu costo a destino",
    "vNoneB": "Añade un precio de venta arriba para ver margen y veredicto.",
    "disclaimer": "Solo estimaciones. El arancel real depende de la clasificación HTS exacta, el origen y la política actual, que cambia a menudo. No es asesoría aduanera ni fiscal. Confirma con un agente de aduanas autorizado.",
    "ctaLine": "Accio Work busca en varios orígenes y gestiona declaraciones de IVA y documentos aduaneros en más de 100 mercados.",
    "cta": "Empieza gratis en Accio Work",
    "ctaNote": "Plan gratuito, sin tarjeta",
    "dUS": "Estados Unidos",
    "dEU": "Unión Europea",
    "dUK": "Reino Unido",
    "metaTitle": "Calculadora de aranceles y costo total tras de minimis | Accio Work",
    "metaDesc": "Calculadora gratis de arancel, IVA y costo total real por unidad tras el fin de la exención de minimis de 800 dólares. ¿Sigue saliendo vender paquete a paquete?"
  },
  "zh": {
    "kicker": "2026 更新",
    "h1": "关税与到岸成本计算器",
    "intro": "800 美元的 de minimis 免税已取消，大多数跨境包裹现在都要缴关税并清关。输入你的数字，看清每件真实成本，以及一件一件发货是否还划算。",
    "productCost": "每件产品成本",
    "units": "本次订单件数",
    "shipping": "运费与货运（合计）",
    "dutyRate": "关税与税率",
    "dutyHint": "按 HTS 编码填你产品的税率。中国原产商品自 2025 年起面临较高的叠加关税。",
    "importTax": "进口增值税或手续费",
    "importHint": "按市场的大致默认值，请按你的情况修改。",
    "sellPrice": "你的每件售价（可选）",
    "destination": "目标市场",
    "dutyAmount": "预估关税",
    "importAmount": "进口增值税与费用",
    "landedUnit": "每件到岸成本",
    "landedTotal": "到岸总成本",
    "marginUnit": "每件毛利",
    "marginPct": "毛利率",
    "vHealthyT": "毛利稳住",
    "vHealthyB": "按此成本仍有可行毛利。留意税率变化与运费。",
    "vTightT": "毛利偏紧",
    "vTightB": "关税和费用吃掉大部分毛利。批量进口到本地仓库可降低每件关税与处理成本。",
    "vUnderT": "该模式亏损",
    "vUnderB": "按此成本，一件一件发货是亏的。批量进口或改换原产国可能是唯一出路。",
    "vNoneT": "你的到岸成本",
    "vNoneB": "在上方填入售价，即可看到毛利与结论。",
    "disclaimer": "仅为估算。实际关税取决于准确的 HTS 归类、原产国和经常变动的现行政策。这不是清关或税务建议，请与持牌报关行确认。",
    "ctaLine": "Accio Work 跨多个原产国寻源，并在 100 多个市场处理增值税申报与清关文件。",
    "cta": "免费开始使用 Accio Work",
    "ctaNote": "免费方案，无需绑定银行卡",
    "dUS": "美国",
    "dEU": "欧盟",
    "dUK": "英国",
    "metaTitle": "de minimis 之后的关税与到岸成本计算器 | Accio Work",
    "metaDesc": "免费计算进口关税、增值税与每件真实到岸成本，适用于 800 美元 de minimis 免税取消之后。看看一件一件发货是否还划算。"
  },
  "pt": {
    "kicker": "Atualizado 2026",
    "h1": "Calculadora de impostos e custo total",
    "intro": "A isenção de minimis de 800 dólares acabou, então a maioria dos pacotes transfronteiriços agora paga imposto e passa pela alfândega. Digite seus números para ver o custo real por unidade e se vender pacote a pacote ainda compensa.",
    "productCost": "Custo do produto por unidade",
    "units": "Unidades neste pedido",
    "shipping": "Frete e transporte (total)",
    "dutyRate": "Alíquota de imposto e tarifa",
    "dutyHint": "Digite a alíquota do seu produto pelo código HTS. Bens de origem chinesa enfrentam altas tarifas acumuladas desde 2025.",
    "importTax": "IVA de importação ou taxas",
    "importHint": "Valor aproximado por mercado. Ajuste ao seu caso.",
    "sellPrice": "Seu preço de venda por unidade (opcional)",
    "destination": "Mercado de destino",
    "dutyAmount": "Imposto estimado",
    "importAmount": "IVA de importação e taxas",
    "landedUnit": "Custo total por unidade",
    "landedTotal": "Custo total a destino",
    "marginUnit": "Margem por unidade",
    "marginPct": "Margem",
    "vHealthyT": "A margem se sustenta",
    "vHealthyB": "A esse custo sobra uma margem viável. Fique de olho em mudanças de alíquota e no frete.",
    "vTightT": "Margem apertada",
    "vTightB": "Imposto e taxas comem quase toda a margem. Importar em volume para um armazém local reduz imposto e manuseio por unidade.",
    "vUnderT": "Modelo no prejuízo",
    "vUnderB": "A esse custo, o caminho pacote a pacote perde dinheiro. Importar em volume ou outra origem podem ser a única saída.",
    "vNoneT": "Seu custo a destino",
    "vNoneB": "Adicione um preço de venda acima para ver margem e veredito.",
    "disclaimer": "Apenas estimativas. O imposto real depende da classificação HTS exata, da origem e da política atual, que muda com frequência. Não é consultoria aduaneira ou fiscal. Confirme com um despachante licenciado.",
    "ctaLine": "O Accio Work busca em várias origens e cuida de declarações de IVA e documentos aduaneiros em mais de 100 mercados.",
    "cta": "Comece grátis no Accio Work",
    "ctaNote": "Plano gratuito, sem cartão",
    "dUS": "Estados Unidos",
    "dEU": "União Europeia",
    "dUK": "Reino Unido",
    "metaTitle": "Calculadora de impostos e custo total após de minimis | Accio Work",
    "metaDesc": "Calculadora grátis de imposto de importação, IVA e custo total real por unidade após o fim da isenção de minimis de 800 dólares."
  },
  "hi": {
    "kicker": "2026 अपडेट",
    "h1": "शुल्क और लैंडेड कॉस्ट कैलकुलेटर",
    "intro": "800 डॉलर की de minimis छूट खत्म हो गई, इसलिए अब ज़्यादातर सीमापार पार्सल पर शुल्क लगता है और कस्टम से गुज़रना पड़ता है। अपने आंकड़े डालें और प्रति यूनिट असली लागत देखें, और यह भी कि एक-एक पार्सल बेचना अब भी फ़ायदेमंद है या नहीं।",
    "productCost": "प्रति यूनिट उत्पाद लागत",
    "units": "इस ऑर्डर में यूनिट",
    "shipping": "शिपिंग और फ्रेट (कुल)",
    "dutyRate": "शुल्क और टैरिफ दर",
    "dutyHint": "अपने उत्पाद की दर उसके HTS कोड से डालें। चीन मूल के सामान पर 2025 से ऊँचे संचयी टैरिफ लगे हैं।",
    "importTax": "आयात VAT या हैंडलिंग",
    "importHint": "बाज़ार के अनुसार मोटा डिफ़ॉल्ट। अपने हिसाब से बदलें।",
    "sellPrice": "आपकी प्रति यूनिट बिक्री कीमत (वैकल्पिक)",
    "destination": "गंतव्य बाज़ार",
    "dutyAmount": "अनुमानित शुल्क",
    "importAmount": "आयात VAT और शुल्क",
    "landedUnit": "प्रति यूनिट लैंडेड कॉस्ट",
    "landedTotal": "कुल लैंडेड कॉस्ट",
    "marginUnit": "प्रति यूनिट मार्जिन",
    "marginPct": "मार्जिन",
    "vHealthyT": "मार्जिन टिका है",
    "vHealthyB": "इस लागत पर काम लायक मार्जिन बचता है। दरों और शिपिंग में बदलाव पर नज़र रखें।",
    "vTightT": "मार्जिन कसा हुआ",
    "vTightB": "शुल्क और फ़ीस लगभग पूरा मार्जिन खा जाते हैं। स्थानीय गोदाम में थोक आयात प्रति यूनिट शुल्क और हैंडलिंग घटाता है।",
    "vUnderT": "यह मॉडल घाटे में",
    "vUnderB": "इस लागत पर एक-एक पार्सल वाला रास्ता घाटे का है। थोक आयात या दूसरा मूल देश ही एकमात्र रास्ता हो सकता है।",
    "vNoneT": "आपकी लैंडेड कॉस्ट",
    "vNoneB": "मार्जिन और नतीजा देखने के लिए ऊपर बिक्री कीमत डालें।",
    "disclaimer": "केवल अनुमान। असली शुल्क सटीक HTS वर्गीकरण, मूल देश और मौजूदा नीति पर निर्भर है, जो अक्सर बदलती है। यह कस्टम या कर सलाह नहीं है। लाइसेंस प्राप्त कस्टम ब्रोकर से पुष्टि करें।",
    "ctaLine": "Accio Work कई मूल देशों से सोर्स करता है और 100+ बाज़ारों में VAT फाइलिंग और कस्टम दस्तावेज़ संभालता है।",
    "cta": "Accio Work मुफ्त में शुरू करें",
    "ctaNote": "मुफ्त प्लान, कार्ड की जरूरत नहीं",
    "dUS": "संयुक्त राज्य",
    "dEU": "यूरोपीय संघ",
    "dUK": "यूनाइटेड किंगडम",
    "metaTitle": "de minimis के बाद शुल्क और लैंडेड कॉस्ट कैलकुलेटर | Accio Work",
    "metaDesc": "800 डॉलर की de minimis छूट खत्म होने के बाद आयात शुल्क, VAT और प्रति यूनिट असली लैंडेड कॉस्ट का मुफ्त कैलकुलेटर। देखें कि एक-एक पार्सल बेचना अब भी फ़ायदेमंद है।"
  },
  "fr": {
    "kicker": "À jour 2026",
    "h1": "Calculateur de droits et coût rendu",
    "intro": "L'exemption de minimis de 800 dollars a disparu, la plupart des colis transfrontaliers paient désormais des droits et passent la douane. Entrez vos chiffres pour voir votre coût réel par unité et si vendre colis par colis reste rentable.",
    "productCost": "Coût du produit par unité",
    "units": "Unités dans cette commande",
    "shipping": "Expédition et fret (total)",
    "dutyRate": "Taux de droit et de tarif",
    "dutyHint": "Entrez le taux de votre produit selon son code HTS. Les biens d'origine chinoise subissent de forts tarifs cumulés depuis 2025.",
    "importTax": "TVA à l'import ou frais",
    "importHint": "Valeur indicative par marché. Adaptez à votre cas.",
    "sellPrice": "Votre prix de vente par unité (facultatif)",
    "destination": "Marché de destination",
    "dutyAmount": "Droit estimé",
    "importAmount": "TVA import et frais",
    "landedUnit": "Coût rendu par unité",
    "landedTotal": "Coût rendu total",
    "marginUnit": "Marge par unité",
    "marginPct": "Marge",
    "vHealthyT": "La marge tient",
    "vHealthyB": "À ce coût il reste une marge viable. Surveillez les changements de taux et l'expédition.",
    "vTightT": "Marge serrée",
    "vTightB": "Droits et frais mangent presque toute la marge. Importer en gros vers un entrepôt local réduit droit et manutention par unité.",
    "vUnderT": "Modèle à perte",
    "vUnderB": "À ce coût, la voie colis par colis perd de l'argent. L'import en gros ou une autre origine peuvent être la seule solution.",
    "vNoneT": "Votre coût rendu",
    "vNoneB": "Ajoutez un prix de vente ci-dessus pour voir la marge et le verdict.",
    "disclaimer": "Estimations seulement. Le droit réel dépend de la classification HTS exacte, de l'origine et de la politique en vigueur, qui change souvent. Ceci n'est pas un conseil douanier ou fiscal. Vérifiez avec un courtier en douane agréé.",
    "ctaLine": "Accio Work source sur plusieurs origines et gère les déclarations de TVA et les documents douaniers dans plus de 100 marchés.",
    "cta": "Commencer gratuitement sur Accio Work",
    "ctaNote": "Offre gratuite, sans carte",
    "dUS": "États-Unis",
    "dEU": "Union européenne",
    "dUK": "Royaume-Uni",
    "metaTitle": "Calculateur de droits et coût rendu après de minimis | Accio Work",
    "metaDesc": "Calculateur gratuit de droits d'import, TVA et coût rendu réel par unité après la fin de l'exemption de minimis de 800 dollars."
  }
};

// Default import VAT / handling estimate per destination (editable in UI).
export const dutyVatDefault: Record<"US" | "EU" | "UK", number> = { US: 0, EU: 21, UK: 20 };
