// AUTO GENERATED calculator strings. Edit gen_roi_data.py to change.
export type RoiLang = "en" | "ru" | "de" | "it" | "es" | "zh" | "pt" | "hi" | "fr";
export interface RoiChrome {
  kicker: string; h1: string; intro: string; tasks: string[]; offload: string; offloadHint: string; hoursUnit: string; hourlyToggle: string; hourlyLabel: string; perHour: string; currency: string; resultKicker: string; freedHours: string; daysYear: string; moneyMonth: string; moneyYear: string; keep: string; agent: string; punch: string; cta: string; ctaNote: string; tryLine: string; disclaimer: string; metaTitle: string; metaDesc: string;
}
export const roiChrome: Record<RoiLang, RoiChrome> = {
  "en": {
    "kicker": "Interactive",
    "h1": "How many hours could an AI agent give you back?",
    "intro": "Drag the sliders to match your week. See the time an agent like Accio Work could take off your plate, and what that time is worth.",
    "tasks": [
      "Supplier sourcing",
      "Market research",
      "Content and marketing",
      "Admin and compliance"
    ],
    "offload": "How much can the agent take off your plate?",
    "offloadHint": "A realistic range for repetitive work. Move it to be cautious or bold.",
    "hoursUnit": "h/week",
    "hourlyToggle": "Add your hourly value (optional)",
    "hourlyLabel": "Your time is worth",
    "perHour": "per hour",
    "currency": "Currency",
    "resultKicker": "Your estimate",
    "freedHours": "hours a week freed",
    "daysYear": "days a year back",
    "moneyMonth": "a month",
    "moneyYear": "a year",
    "keep": "You keep",
    "agent": "Agent takes",
    "punch": "That is about {days} days a year you could spend on growth instead of grind.",
    "cta": "Start free on Accio Work",
    "ctaNote": "Free plan, no card required",
    "tryLine": "Put a real task on it and see for yourself.",
    "disclaimer": "This is a rough estimate, not a promise. An AI agent assists with repeatable work, it does not replace your judgment. Results vary, and Accio Work fits cross border sellers best.",
    "metaTitle": "AI agent time savings calculator | Accio Work",
    "metaDesc": "Estimate how many hours a week an AI agent like Accio Work could free up across sourcing, research, content and admin, and what that time is worth. Free to try."
  },
  "ru": {
    "kicker": "Интерактив",
    "h1": "Сколько часов вам вернёт AI-агент?",
    "intro": "Двигайте ползунки под свою неделю. Увидите, сколько времени агент вроде Accio Work может снять с вас, и сколько это стоит.",
    "tasks": [
      "Поиск поставщиков",
      "Анализ рынка",
      "Контент и маркетинг",
      "Админка и документы"
    ],
    "offload": "Сколько агент может взять на себя?",
    "offloadHint": "Реалистичный диапазон для рутины. Сдвиньте осторожнее или смелее.",
    "hoursUnit": "ч/нед",
    "hourlyToggle": "Добавить стоимость часа (необязательно)",
    "hourlyLabel": "Ваш час стоит",
    "perHour": "в час",
    "currency": "Валюта",
    "resultKicker": "Ваша оценка",
    "freedHours": "часов в неделю свободно",
    "daysYear": "дней в году назад",
    "moneyMonth": "в месяц",
    "moneyYear": "в год",
    "keep": "Оставляете себе",
    "agent": "Берёт агент",
    "punch": "Это около {days} дней в году, которые можно тратить на рост, а не на рутину.",
    "cta": "Начать бесплатно в Accio Work",
    "ctaNote": "Бесплатный план, карта не нужна",
    "tryLine": "Дайте ему реальную задачу и проверьте сами.",
    "disclaimer": "Это грубая оценка, а не обещание. AI-агент помогает с повторяющейся работой, но не заменяет ваши решения. Результат разный, и Accio Work лучше всего подходит трансграничной торговле.",
    "metaTitle": "Калькулятор экономии времени с AI-агентом | Accio Work",
    "metaDesc": "Оцените, сколько часов в неделю агент вроде Accio Work может освободить на поиске поставщиков, анализе, контенте и админке, и сколько это стоит."
  },
  "de": {
    "kicker": "Interaktiv",
    "h1": "Wie viele Stunden könnte dir ein AI-Agent zurückgeben?",
    "intro": "Zieh die Regler passend zu deiner Woche. Sieh, wie viel Zeit ein Agent wie Accio Work dir abnehmen kann und was diese Zeit wert ist.",
    "tasks": [
      "Lieferantensuche",
      "Marktforschung",
      "Content und Marketing",
      "Verwaltung und Compliance"
    ],
    "offload": "Wie viel kann der Agent übernehmen?",
    "offloadHint": "Ein realistischer Bereich für Routine. Vorsichtig oder mutig einstellen.",
    "hoursUnit": "Std/Woche",
    "hourlyToggle": "Stundenwert hinzufügen (optional)",
    "hourlyLabel": "Deine Zeit ist wert",
    "perHour": "pro Stunde",
    "currency": "Währung",
    "resultKicker": "Deine Schätzung",
    "freedHours": "Stunden pro Woche frei",
    "daysYear": "Tage im Jahr zurück",
    "moneyMonth": "im Monat",
    "moneyYear": "im Jahr",
    "keep": "Du behältst",
    "agent": "Agent nimmt",
    "punch": "Das sind rund {days} Tage im Jahr für Wachstum statt Kleinarbeit.",
    "cta": "Kostenlos mit Accio Work starten",
    "ctaNote": "Kostenloser Plan, keine Karte nötig",
    "tryLine": "Gib ihm eine echte Aufgabe und überzeug dich selbst.",
    "disclaimer": "Das ist eine grobe Schätzung, kein Versprechen. Ein AI-Agent hilft bei wiederkehrender Arbeit, er ersetzt dein Urteil nicht. Ergebnisse variieren, und Accio Work passt am besten zu grenzüberschreitenden Verkäufern.",
    "metaTitle": "AI-Agent Zeitersparnis Rechner | Accio Work",
    "metaDesc": "Schätze, wie viele Stunden pro Woche ein Agent wie Accio Work bei Sourcing, Recherche, Content und Verwaltung freimacht und was das wert ist. Gratis testen."
  },
  "it": {
    "kicker": "Interattivo",
    "h1": "Quante ore potrebbe restituirti un agente AI?",
    "intro": "Trascina i cursori sulla tua settimana. Guarda quanto tempo un agente come Accio Work può toglierti e quanto vale.",
    "tasks": [
      "Ricerca fornitori",
      "Ricerca di mercato",
      "Contenuti e marketing",
      "Gestione e conformità"
    ],
    "offload": "Quanto può prendersi in carico l'agente?",
    "offloadHint": "Un intervallo realistico per la routine. Spostalo cauto o audace.",
    "hoursUnit": "h/sett",
    "hourlyToggle": "Aggiungi il valore orario (facoltativo)",
    "hourlyLabel": "Il tuo tempo vale",
    "perHour": "all'ora",
    "currency": "Valuta",
    "resultKicker": "La tua stima",
    "freedHours": "ore a settimana libere",
    "daysYear": "giorni all'anno recuperati",
    "moneyMonth": "al mese",
    "moneyYear": "all'anno",
    "keep": "Tieni tu",
    "agent": "Prende l'agente",
    "punch": "Sono circa {days} giorni all'anno da dedicare alla crescita invece che alla fatica.",
    "cta": "Inizia gratis su Accio Work",
    "ctaNote": "Piano gratuito, nessuna carta richiesta",
    "tryLine": "Dagli un compito vero e verifica di persona.",
    "disclaimer": "È una stima approssimativa, non una promessa. Un agente AI aiuta col lavoro ripetitivo, non sostituisce il tuo giudizio. I risultati variano e Accio Work si adatta meglio ai venditori transfrontalieri.",
    "metaTitle": "Calcolatore di risparmio tempo con agente AI | Accio Work",
    "metaDesc": "Stima quante ore a settimana un agente come Accio Work può liberare tra sourcing, ricerca, contenuti e gestione, e quanto vale. Prova gratis."
  },
  "es": {
    "kicker": "Interactivo",
    "h1": "¿Cuántas horas podría devolverte un agente de IA?",
    "intro": "Arrastra los controles a tu semana. Mira cuánto tiempo un agente como Accio Work puede quitarte de encima y cuánto vale.",
    "tasks": [
      "Sourcing de proveedores",
      "Investigación de mercado",
      "Contenido y marketing",
      "Administración y cumplimiento"
    ],
    "offload": "¿Cuánto puede asumir el agente?",
    "offloadHint": "Un rango realista para lo repetitivo. Muévelo cauto o audaz.",
    "hoursUnit": "h/sem",
    "hourlyToggle": "Añade tu valor por hora (opcional)",
    "hourlyLabel": "Tu tiempo vale",
    "perHour": "por hora",
    "currency": "Moneda",
    "resultKicker": "Tu estimación",
    "freedHours": "horas a la semana libres",
    "daysYear": "días al año de vuelta",
    "moneyMonth": "al mes",
    "moneyYear": "al año",
    "keep": "Te quedas",
    "agent": "Toma el agente",
    "punch": "Son unos {days} días al año para crecer en vez de batallar.",
    "cta": "Empieza gratis en Accio Work",
    "ctaNote": "Plan gratuito, sin tarjeta",
    "tryLine": "Ponle una tarea real y compruébalo.",
    "disclaimer": "Es una estimación aproximada, no una promesa. Un agente de IA ayuda con lo repetitivo, no reemplaza tu criterio. Los resultados varían y Accio Work encaja mejor con vendedores transfronterizos.",
    "metaTitle": "Calculadora de ahorro de tiempo con agente de IA | Accio Work",
    "metaDesc": "Estima cuántas horas por semana un agente como Accio Work puede liberar en sourcing, investigación, contenido y administración, y cuánto vale. Prueba gratis."
  },
  "zh": {
    "kicker": "互动",
    "h1": "AI 智能体能帮你省回多少小时？",
    "intro": "拖动滑块贴合你的一周。看看像 Accio Work 这样的智能体能替你分担多少时间，以及这些时间值多少。",
    "tasks": [
      "供应商寻源",
      "市场调研",
      "内容与营销",
      "行政与合规"
    ],
    "offload": "智能体能分担多少？",
    "offloadHint": "针对重复工作的现实区间。可保守也可激进。",
    "hoursUnit": "小时/周",
    "hourlyToggle": "填写你的时薪（可选）",
    "hourlyLabel": "你的时间价值",
    "perHour": "每小时",
    "currency": "币种",
    "resultKicker": "你的估算",
    "freedHours": "每周省出的小时",
    "daysYear": "每年拿回的天数",
    "moneyMonth": "每月",
    "moneyYear": "每年",
    "keep": "你自己留",
    "agent": "智能体承担",
    "punch": "大约相当于每年 {days} 天，可以用来做增长而不是琐事。",
    "cta": "免费开始使用 Accio Work",
    "ctaNote": "免费方案，无需绑定银行卡",
    "tryLine": "给它一个真实任务，自己看看效果。",
    "disclaimer": "这是粗略估算，并非承诺。AI 智能体帮你处理重复工作，不能替代你的判断。结果因人而异，Accio Work 最适合跨境卖家。",
    "metaTitle": "AI 智能体省时计算器 | Accio Work",
    "metaDesc": "估算像 Accio Work 这样的智能体每周能在寻源、调研、内容和行政上省出多少小时，以及价值几何。免费试用。"
  },
  "pt": {
    "kicker": "Interativo",
    "h1": "Quantas horas um agente de IA poderia te devolver?",
    "intro": "Arraste os controles conforme sua semana. Veja quanto tempo um agente como o Accio Work pode tirar do seu colo e quanto isso vale.",
    "tasks": [
      "Sourcing de fornecedores",
      "Pesquisa de mercado",
      "Conteúdo e marketing",
      "Administração e conformidade"
    ],
    "offload": "Quanto o agente pode assumir?",
    "offloadHint": "Uma faixa realista para o repetitivo. Mova cauteloso ou ousado.",
    "hoursUnit": "h/sem",
    "hourlyToggle": "Adicione seu valor por hora (opcional)",
    "hourlyLabel": "Seu tempo vale",
    "perHour": "por hora",
    "currency": "Moeda",
    "resultKicker": "Sua estimativa",
    "freedHours": "horas por semana livres",
    "daysYear": "dias por ano de volta",
    "moneyMonth": "por mês",
    "moneyYear": "por ano",
    "keep": "Você fica",
    "agent": "Agente assume",
    "punch": "São cerca de {days} dias por ano para crescer em vez de se desgastar.",
    "cta": "Comece grátis no Accio Work",
    "ctaNote": "Plano gratuito, sem cartão",
    "tryLine": "Dê a ele uma tarefa real e comprove.",
    "disclaimer": "É uma estimativa aproximada, não uma promessa. Um agente de IA ajuda no trabalho repetitivo, não substitui seu julgamento. Os resultados variam e o Accio Work combina mais com vendedores transfronteiriços.",
    "metaTitle": "Calculadora de economia de tempo com agente de IA | Accio Work",
    "metaDesc": "Estime quantas horas por semana um agente como o Accio Work pode liberar em sourcing, pesquisa, conteúdo e administração, e quanto vale. Teste grátis."
  },
  "hi": {
    "kicker": "इंटरैक्टिव",
    "h1": "एक AI एजेंट आपको कितने घंटे लौटा सकता है?",
    "intro": "स्लाइडर को अपने हफ्ते के हिसाब से खिसकाएं। देखें कि Accio Work जैसा एजेंट कितना समय आपके कंधों से उतार सकता है, और वह कितने का है।",
    "tasks": [
      "सप्लायर सोर्सिंग",
      "मार्केट रिसर्च",
      "कंटेंट और मार्केटिंग",
      "प्रशासन और अनुपालन"
    ],
    "offload": "एजेंट कितना संभाल सकता है?",
    "offloadHint": "दोहराव वाले काम के लिए यथार्थ रेंज। सतर्क या साहसी रखें।",
    "hoursUnit": "घंटे/हफ्ता",
    "hourlyToggle": "अपना प्रति घंटा मूल्य जोड़ें (वैकल्पिक)",
    "hourlyLabel": "आपका समय मूल्य",
    "perHour": "प्रति घंटा",
    "currency": "मुद्रा",
    "resultKicker": "आपका अनुमान",
    "freedHours": "हफ्ते के मुक्त घंटे",
    "daysYear": "साल में वापस मिले दिन",
    "moneyMonth": "प्रति माह",
    "moneyYear": "प्रति वर्ष",
    "keep": "आप रखते हैं",
    "agent": "एजेंट लेता है",
    "punch": "यानी साल में लगभग {days} दिन, जो रगड़ के बजाय ग्रोथ पर लगा सकते हैं।",
    "cta": "Accio Work मुफ्त में शुरू करें",
    "ctaNote": "मुफ्त प्लान, कार्ड की जरूरत नहीं",
    "tryLine": "इसे एक असली काम दें और खुद देखें।",
    "disclaimer": "यह मोटा अनुमान है, वादा नहीं। AI एजेंट दोहराव वाले काम में मदद करता है, आपका निर्णय नहीं लेता। नतीजे अलग होते हैं, और Accio Work सीमापार विक्रेताओं के लिए सबसे उपयुक्त है।",
    "metaTitle": "AI एजेंट समय बचत कैलकुलेटर | Accio Work",
    "metaDesc": "अनुमान लगाएं कि Accio Work जैसा एजेंट सोर्सिंग, रिसर्च, कंटेंट और प्रशासन में हफ्ते के कितने घंटे मुक्त कर सकता है, और वह कितने का है। मुफ्त आज़माएं।"
  },
  "fr": {
    "kicker": "Interactif",
    "h1": "Combien d'heures un agent IA pourrait-il vous rendre ?",
    "intro": "Faites glisser les curseurs selon votre semaine. Voyez le temps qu'un agent comme Accio Work peut vous enlever, et ce qu'il vaut.",
    "tasks": [
      "Sourcing fournisseurs",
      "Étude de marché",
      "Contenu et marketing",
      "Administration et conformité"
    ],
    "offload": "Combien l'agent peut-il prendre en charge ?",
    "offloadHint": "Une fourchette réaliste pour la routine. Prudent ou audacieux, à vous.",
    "hoursUnit": "h/sem",
    "hourlyToggle": "Ajoutez votre valeur horaire (facultatif)",
    "hourlyLabel": "Votre temps vaut",
    "perHour": "de l'heure",
    "currency": "Devise",
    "resultKicker": "Votre estimation",
    "freedHours": "heures par semaine libérées",
    "daysYear": "jours par an récupérés",
    "moneyMonth": "par mois",
    "moneyYear": "par an",
    "keep": "Vous gardez",
    "agent": "L'agent prend",
    "punch": "Soit environ {days} jours par an à consacrer à la croissance plutôt qu'à la corvée.",
    "cta": "Commencer gratuitement sur Accio Work",
    "ctaNote": "Offre gratuite, sans carte",
    "tryLine": "Donnez-lui une vraie tâche et jugez par vous-même.",
    "disclaimer": "C'est une estimation approximative, pas une promesse. Un agent IA aide sur le travail répétitif, il ne remplace pas votre jugement. Les résultats varient et Accio Work convient surtout aux vendeurs transfrontaliers.",
    "metaTitle": "Calculateur de gain de temps avec agent IA | Accio Work",
    "metaDesc": "Estimez combien d'heures par semaine un agent comme Accio Work peut libérer sur le sourcing, la recherche, le contenu et l'administration, et ce que ça vaut."
  }
};
