/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuRouteImport } from './routes/ru'
import { Route as PtRouteImport } from './routes/pt'
import { Route as ItRouteImport } from './routes/it'
import { Route as HiRouteImport } from './routes/hi'
import { Route as EsRouteImport } from './routes/es'
import { Route as DeRouteImport } from './routes/de'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh.index'
import { Route as RuIndexRouteImport } from './routes/ru.index'
import { Route as PtIndexRouteImport } from './routes/pt.index'
import { Route as ItIndexRouteImport } from './routes/it.index'
import { Route as HiIndexRouteImport } from './routes/hi.index'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as DeIndexRouteImport } from './routes/de.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as EventsFreeForeverRouteImport } from './routes/events.free-forever'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ZhBlogIndexRouteImport } from './routes/zh.blog.index'
import { Route as RuBlogIndexRouteImport } from './routes/ru.blog.index'
import { Route as PtBlogIndexRouteImport } from './routes/pt.blog.index'
import { Route as ItBlogIndexRouteImport } from './routes/it.blog.index'
import { Route as HiBlogIndexRouteImport } from './routes/hi.blog.index'
import { Route as EsBlogIndexRouteImport } from './routes/es.blog.index'
import { Route as DeBlogIndexRouteImport } from './routes/de.blog.index'
import { Route as ZhEventsFreeForeverRouteImport } from './routes/zh.events.free-forever'
import { Route as ZhBlogSlugRouteImport } from './routes/zh.blog.$slug'
import { Route as RuEventsFreeForeverRouteImport } from './routes/ru.events.free-forever'
import { Route as RuBlogSlugRouteImport } from './routes/ru.blog.$slug'
import { Route as PtEventsFreeForeverRouteImport } from './routes/pt.events.free-forever'
import { Route as PtBlogSlugRouteImport } from './routes/pt.blog.$slug'
import { Route as ItEventsFreeForeverRouteImport } from './routes/it.events.free-forever'
import { Route as ItBlogSlugRouteImport } from './routes/it.blog.$slug'
import { Route as HiEventsFreeForeverRouteImport } from './routes/hi.events.free-forever'
import { Route as HiBlogSlugRouteImport } from './routes/hi.blog.$slug'
import { Route as EsEventsFreeForeverRouteImport } from './routes/es.events.free-forever'
import { Route as EsBlogSlugRouteImport } from './routes/es.blog.$slug'
import { Route as DeEventsFreeForeverRouteImport } from './routes/de.events.free-forever'
import { Route as DeBlogSlugRouteImport } from './routes/de.blog.$slug'
import { Route as ApiPublicCronGenerateArticlesRouteImport } from './routes/api/public/cron/generate-articles'

const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const HiRoute = HiRouteImport.update({
  id: '/hi',
  path: '/hi',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhRoute,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuRoute,
} as any)
const PtIndexRoute = PtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtRoute,
} as any)
const ItIndexRoute = ItIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItRoute,
} as any)
const HiIndexRoute = HiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HiRoute,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsFreeForeverRoute = EventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhBlogIndexRoute = ZhBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ZhRoute,
} as any)
const RuBlogIndexRoute = RuBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => RuRoute,
} as any)
const PtBlogIndexRoute = PtBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PtRoute,
} as any)
const ItBlogIndexRoute = ItBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ItRoute,
} as any)
const HiBlogIndexRoute = HiBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => HiRoute,
} as any)
const EsBlogIndexRoute = EsBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => EsRoute,
} as any)
const DeBlogIndexRoute = DeBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DeRoute,
} as any)
const ZhEventsFreeForeverRoute = ZhEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => ZhRoute,
} as any)
const ZhBlogSlugRoute = ZhBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ZhRoute,
} as any)
const RuEventsFreeForeverRoute = RuEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => RuRoute,
} as any)
const RuBlogSlugRoute = RuBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => RuRoute,
} as any)
const PtEventsFreeForeverRoute = PtEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => PtRoute,
} as any)
const PtBlogSlugRoute = PtBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PtRoute,
} as any)
const ItEventsFreeForeverRoute = ItEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => ItRoute,
} as any)
const ItBlogSlugRoute = ItBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ItRoute,
} as any)
const HiEventsFreeForeverRoute = HiEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => HiRoute,
} as any)
const HiBlogSlugRoute = HiBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => HiRoute,
} as any)
const EsEventsFreeForeverRoute = EsEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => EsRoute,
} as any)
const EsBlogSlugRoute = EsBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => EsRoute,
} as any)
const DeEventsFreeForeverRoute = DeEventsFreeForeverRouteImport.update({
  id: '/events/free-forever',
  path: '/events/free-forever',
  getParentRoute: () => DeRoute,
} as any)
const DeBlogSlugRoute = DeBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => DeRoute,
} as any)
const ApiPublicCronGenerateArticlesRoute =
  ApiPublicCronGenerateArticlesRouteImport.update({
    id: '/api/public/cron/generate-articles',
    path: '/api/public/cron/generate-articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de': typeof DeRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/hi': typeof HiRouteWithChildren
  '/it': typeof ItRouteWithChildren
  '/pt': typeof PtRouteWithChildren
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/events/free-forever': typeof EventsFreeForeverRoute
  '/blog/': typeof BlogIndexRoute
  '/de/': typeof DeIndexRoute
  '/es/': typeof EsIndexRoute
  '/hi/': typeof HiIndexRoute
  '/it/': typeof ItIndexRoute
  '/pt/': typeof PtIndexRoute
  '/ru/': typeof RuIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/de/blog/$slug': typeof DeBlogSlugRoute
  '/de/events/free-forever': typeof DeEventsFreeForeverRoute
  '/es/blog/$slug': typeof EsBlogSlugRoute
  '/es/events/free-forever': typeof EsEventsFreeForeverRoute
  '/hi/blog/$slug': typeof HiBlogSlugRoute
  '/hi/events/free-forever': typeof HiEventsFreeForeverRoute
  '/it/blog/$slug': typeof ItBlogSlugRoute
  '/it/events/free-forever': typeof ItEventsFreeForeverRoute
  '/pt/blog/$slug': typeof PtBlogSlugRoute
  '/pt/events/free-forever': typeof PtEventsFreeForeverRoute
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/events/free-forever': typeof RuEventsFreeForeverRoute
  '/zh/blog/$slug': typeof ZhBlogSlugRoute
  '/zh/events/free-forever': typeof ZhEventsFreeForeverRoute
  '/de/blog/': typeof DeBlogIndexRoute
  '/es/blog/': typeof EsBlogIndexRoute
  '/hi/blog/': typeof HiBlogIndexRoute
  '/it/blog/': typeof ItBlogIndexRoute
  '/pt/blog/': typeof PtBlogIndexRoute
  '/ru/blog/': typeof RuBlogIndexRoute
  '/zh/blog/': typeof ZhBlogIndexRoute
  '/api/public/cron/generate-articles': typeof ApiPublicCronGenerateArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/free-forever': typeof EventsFreeForeverRoute
  '/blog': typeof BlogIndexRoute
  '/de': typeof DeIndexRoute
  '/es': typeof EsIndexRoute
  '/hi': typeof HiIndexRoute
  '/it': typeof ItIndexRoute
  '/pt': typeof PtIndexRoute
  '/ru': typeof RuIndexRoute
  '/zh': typeof ZhIndexRoute
  '/de/blog/$slug': typeof DeBlogSlugRoute
  '/de/events/free-forever': typeof DeEventsFreeForeverRoute
  '/es/blog/$slug': typeof EsBlogSlugRoute
  '/es/events/free-forever': typeof EsEventsFreeForeverRoute
  '/hi/blog/$slug': typeof HiBlogSlugRoute
  '/hi/events/free-forever': typeof HiEventsFreeForeverRoute
  '/it/blog/$slug': typeof ItBlogSlugRoute
  '/it/events/free-forever': typeof ItEventsFreeForeverRoute
  '/pt/blog/$slug': typeof PtBlogSlugRoute
  '/pt/events/free-forever': typeof PtEventsFreeForeverRoute
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/events/free-forever': typeof RuEventsFreeForeverRoute
  '/zh/blog/$slug': typeof ZhBlogSlugRoute
  '/zh/events/free-forever': typeof ZhEventsFreeForeverRoute
  '/de/blog': typeof DeBlogIndexRoute
  '/es/blog': typeof EsBlogIndexRoute
  '/hi/blog': typeof HiBlogIndexRoute
  '/it/blog': typeof ItBlogIndexRoute
  '/pt/blog': typeof PtBlogIndexRoute
  '/ru/blog': typeof RuBlogIndexRoute
  '/zh/blog': typeof ZhBlogIndexRoute
  '/api/public/cron/generate-articles': typeof ApiPublicCronGenerateArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de': typeof DeRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/hi': typeof HiRouteWithChildren
  '/it': typeof ItRouteWithChildren
  '/pt': typeof PtRouteWithChildren
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/events/free-forever': typeof EventsFreeForeverRoute
  '/blog/': typeof BlogIndexRoute
  '/de/': typeof DeIndexRoute
  '/es/': typeof EsIndexRoute
  '/hi/': typeof HiIndexRoute
  '/it/': typeof ItIndexRoute
  '/pt/': typeof PtIndexRoute
  '/ru/': typeof RuIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/de/blog/$slug': typeof DeBlogSlugRoute
  '/de/events/free-forever': typeof DeEventsFreeForeverRoute
  '/es/blog/$slug': typeof EsBlogSlugRoute
  '/es/events/free-forever': typeof EsEventsFreeForeverRoute
  '/hi/blog/$slug': typeof HiBlogSlugRoute
  '/hi/events/free-forever': typeof HiEventsFreeForeverRoute
  '/it/blog/$slug': typeof ItBlogSlugRoute
  '/it/events/free-forever': typeof ItEventsFreeForeverRoute
  '/pt/blog/$slug': typeof PtBlogSlugRoute
  '/pt/events/free-forever': typeof PtEventsFreeForeverRoute
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/events/free-forever': typeof RuEventsFreeForeverRoute
  '/zh/blog/$slug': typeof ZhBlogSlugRoute
  '/zh/events/free-forever': typeof ZhEventsFreeForeverRoute
  '/de/blog/': typeof DeBlogIndexRoute
  '/es/blog/': typeof EsBlogIndexRoute
  '/hi/blog/': typeof HiBlogIndexRoute
  '/it/blog/': typeof ItBlogIndexRoute
  '/pt/blog/': typeof PtBlogIndexRoute
  '/ru/blog/': typeof RuBlogIndexRoute
  '/zh/blog/': typeof ZhBlogIndexRoute
  '/api/public/cron/generate-articles': typeof ApiPublicCronGenerateArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de'
    | '/es'
    | '/hi'
    | '/it'
    | '/pt'
    | '/ru'
    | '/sitemap.xml'
    | '/zh'
    | '/blog/$slug'
    | '/events/free-forever'
    | '/blog/'
    | '/de/'
    | '/es/'
    | '/hi/'
    | '/it/'
    | '/pt/'
    | '/ru/'
    | '/zh/'
    | '/de/blog/$slug'
    | '/de/events/free-forever'
    | '/es/blog/$slug'
    | '/es/events/free-forever'
    | '/hi/blog/$slug'
    | '/hi/events/free-forever'
    | '/it/blog/$slug'
    | '/it/events/free-forever'
    | '/pt/blog/$slug'
    | '/pt/events/free-forever'
    | '/ru/blog/$slug'
    | '/ru/events/free-forever'
    | '/zh/blog/$slug'
    | '/zh/events/free-forever'
    | '/de/blog/'
    | '/es/blog/'
    | '/hi/blog/'
    | '/it/blog/'
    | '/pt/blog/'
    | '/ru/blog/'
    | '/zh/blog/'
    | '/api/public/cron/generate-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/events/free-forever'
    | '/blog'
    | '/de'
    | '/es'
    | '/hi'
    | '/it'
    | '/pt'
    | '/ru'
    | '/zh'
    | '/de/blog/$slug'
    | '/de/events/free-forever'
    | '/es/blog/$slug'
    | '/es/events/free-forever'
    | '/hi/blog/$slug'
    | '/hi/events/free-forever'
    | '/it/blog/$slug'
    | '/it/events/free-forever'
    | '/pt/blog/$slug'
    | '/pt/events/free-forever'
    | '/ru/blog/$slug'
    | '/ru/events/free-forever'
    | '/zh/blog/$slug'
    | '/zh/events/free-forever'
    | '/de/blog'
    | '/es/blog'
    | '/hi/blog'
    | '/it/blog'
    | '/pt/blog'
    | '/ru/blog'
    | '/zh/blog'
    | '/api/public/cron/generate-articles'
  id:
    | '__root__'
    | '/'
    | '/de'
    | '/es'
    | '/hi'
    | '/it'
    | '/pt'
    | '/ru'
    | '/sitemap.xml'
    | '/zh'
    | '/blog/$slug'
    | '/events/free-forever'
    | '/blog/'
    | '/de/'
    | '/es/'
    | '/hi/'
    | '/it/'
    | '/pt/'
    | '/ru/'
    | '/zh/'
    | '/de/blog/$slug'
    | '/de/events/free-forever'
    | '/es/blog/$slug'
    | '/es/events/free-forever'
    | '/hi/blog/$slug'
    | '/hi/events/free-forever'
    | '/it/blog/$slug'
    | '/it/events/free-forever'
    | '/pt/blog/$slug'
    | '/pt/events/free-forever'
    | '/ru/blog/$slug'
    | '/ru/events/free-forever'
    | '/zh/blog/$slug'
    | '/zh/events/free-forever'
    | '/de/blog/'
    | '/es/blog/'
    | '/hi/blog/'
    | '/it/blog/'
    | '/pt/blog/'
    | '/ru/blog/'
    | '/zh/blog/'
    | '/api/public/cron/generate-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeRoute: typeof DeRouteWithChildren
  EsRoute: typeof EsRouteWithChildren
  HiRoute: typeof HiRouteWithChildren
  ItRoute: typeof ItRouteWithChildren
  PtRoute: typeof PtRouteWithChildren
  RuRoute: typeof RuRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZhRoute: typeof ZhRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  EventsFreeForeverRoute: typeof EventsFreeForeverRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicCronGenerateArticlesRoute: typeof ApiPublicCronGenerateArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hi': {
      id: '/hi'
      path: '/hi'
      fullPath: '/hi'
      preLoaderRoute: typeof HiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof ZhRoute
    }
    '/ru/': {
      id: '/ru/'
      path: '/'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof RuRoute
    }
    '/pt/': {
      id: '/pt/'
      path: '/'
      fullPath: '/pt/'
      preLoaderRoute: typeof PtIndexRouteImport
      parentRoute: typeof PtRoute
    }
    '/it/': {
      id: '/it/'
      path: '/'
      fullPath: '/it/'
      preLoaderRoute: typeof ItIndexRouteImport
      parentRoute: typeof ItRoute
    }
    '/hi/': {
      id: '/hi/'
      path: '/'
      fullPath: '/hi/'
      preLoaderRoute: typeof HiIndexRouteImport
      parentRoute: typeof HiRoute
    }
    '/es/': {
      id: '/es/'
      path: '/'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/de/': {
      id: '/de/'
      path: '/'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof DeRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/free-forever': {
      id: '/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/events/free-forever'
      preLoaderRoute: typeof EventsFreeForeverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/blog/': {
      id: '/zh/blog/'
      path: '/blog'
      fullPath: '/zh/blog/'
      preLoaderRoute: typeof ZhBlogIndexRouteImport
      parentRoute: typeof ZhRoute
    }
    '/ru/blog/': {
      id: '/ru/blog/'
      path: '/blog'
      fullPath: '/ru/blog/'
      preLoaderRoute: typeof RuBlogIndexRouteImport
      parentRoute: typeof RuRoute
    }
    '/pt/blog/': {
      id: '/pt/blog/'
      path: '/blog'
      fullPath: '/pt/blog/'
      preLoaderRoute: typeof PtBlogIndexRouteImport
      parentRoute: typeof PtRoute
    }
    '/it/blog/': {
      id: '/it/blog/'
      path: '/blog'
      fullPath: '/it/blog/'
      preLoaderRoute: typeof ItBlogIndexRouteImport
      parentRoute: typeof ItRoute
    }
    '/hi/blog/': {
      id: '/hi/blog/'
      path: '/blog'
      fullPath: '/hi/blog/'
      preLoaderRoute: typeof HiBlogIndexRouteImport
      parentRoute: typeof HiRoute
    }
    '/es/blog/': {
      id: '/es/blog/'
      path: '/blog'
      fullPath: '/es/blog/'
      preLoaderRoute: typeof EsBlogIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/de/blog/': {
      id: '/de/blog/'
      path: '/blog'
      fullPath: '/de/blog/'
      preLoaderRoute: typeof DeBlogIndexRouteImport
      parentRoute: typeof DeRoute
    }
    '/zh/events/free-forever': {
      id: '/zh/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/zh/events/free-forever'
      preLoaderRoute: typeof ZhEventsFreeForeverRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/blog/$slug': {
      id: '/zh/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/zh/blog/$slug'
      preLoaderRoute: typeof ZhBlogSlugRouteImport
      parentRoute: typeof ZhRoute
    }
    '/ru/events/free-forever': {
      id: '/ru/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/ru/events/free-forever'
      preLoaderRoute: typeof RuEventsFreeForeverRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/blog/$slug': {
      id: '/ru/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/ru/blog/$slug'
      preLoaderRoute: typeof RuBlogSlugRouteImport
      parentRoute: typeof RuRoute
    }
    '/pt/events/free-forever': {
      id: '/pt/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/pt/events/free-forever'
      preLoaderRoute: typeof PtEventsFreeForeverRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/blog/$slug': {
      id: '/pt/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/pt/blog/$slug'
      preLoaderRoute: typeof PtBlogSlugRouteImport
      parentRoute: typeof PtRoute
    }
    '/it/events/free-forever': {
      id: '/it/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/it/events/free-forever'
      preLoaderRoute: typeof ItEventsFreeForeverRouteImport
      parentRoute: typeof ItRoute
    }
    '/it/blog/$slug': {
      id: '/it/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/it/blog/$slug'
      preLoaderRoute: typeof ItBlogSlugRouteImport
      parentRoute: typeof ItRoute
    }
    '/hi/events/free-forever': {
      id: '/hi/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/hi/events/free-forever'
      preLoaderRoute: typeof HiEventsFreeForeverRouteImport
      parentRoute: typeof HiRoute
    }
    '/hi/blog/$slug': {
      id: '/hi/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/hi/blog/$slug'
      preLoaderRoute: typeof HiBlogSlugRouteImport
      parentRoute: typeof HiRoute
    }
    '/es/events/free-forever': {
      id: '/es/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/es/events/free-forever'
      preLoaderRoute: typeof EsEventsFreeForeverRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/blog/$slug': {
      id: '/es/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/es/blog/$slug'
      preLoaderRoute: typeof EsBlogSlugRouteImport
      parentRoute: typeof EsRoute
    }
    '/de/events/free-forever': {
      id: '/de/events/free-forever'
      path: '/events/free-forever'
      fullPath: '/de/events/free-forever'
      preLoaderRoute: typeof DeEventsFreeForeverRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/blog/$slug': {
      id: '/de/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/de/blog/$slug'
      preLoaderRoute: typeof DeBlogSlugRouteImport
      parentRoute: typeof DeRoute
    }
    '/api/public/cron/generate-articles': {
      id: '/api/public/cron/generate-articles'
      path: '/api/public/cron/generate-articles'
      fullPath: '/api/public/cron/generate-articles'
      preLoaderRoute: typeof ApiPublicCronGenerateArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeRouteChildren {
  DeIndexRoute: typeof DeIndexRoute
  DeBlogSlugRoute: typeof DeBlogSlugRoute
  DeEventsFreeForeverRoute: typeof DeEventsFreeForeverRoute
  DeBlogIndexRoute: typeof DeBlogIndexRoute
}

const DeRouteChildren: DeRouteChildren = {
  DeIndexRoute: DeIndexRoute,
  DeBlogSlugRoute: DeBlogSlugRoute,
  DeEventsFreeForeverRoute: DeEventsFreeForeverRoute,
  DeBlogIndexRoute: DeBlogIndexRoute,
}

const DeRouteWithChildren = DeRoute._addFileChildren(DeRouteChildren)

interface EsRouteChildren {
  EsIndexRoute: typeof EsIndexRoute
  EsBlogSlugRoute: typeof EsBlogSlugRoute
  EsEventsFreeForeverRoute: typeof EsEventsFreeForeverRoute
  EsBlogIndexRoute: typeof EsBlogIndexRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsIndexRoute: EsIndexRoute,
  EsBlogSlugRoute: EsBlogSlugRoute,
  EsEventsFreeForeverRoute: EsEventsFreeForeverRoute,
  EsBlogIndexRoute: EsBlogIndexRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

interface HiRouteChildren {
  HiIndexRoute: typeof HiIndexRoute
  HiBlogSlugRoute: typeof HiBlogSlugRoute
  HiEventsFreeForeverRoute: typeof HiEventsFreeForeverRoute
  HiBlogIndexRoute: typeof HiBlogIndexRoute
}

const HiRouteChildren: HiRouteChildren = {
  HiIndexRoute: HiIndexRoute,
  HiBlogSlugRoute: HiBlogSlugRoute,
  HiEventsFreeForeverRoute: HiEventsFreeForeverRoute,
  HiBlogIndexRoute: HiBlogIndexRoute,
}

const HiRouteWithChildren = HiRoute._addFileChildren(HiRouteChildren)

interface ItRouteChildren {
  ItIndexRoute: typeof ItIndexRoute
  ItBlogSlugRoute: typeof ItBlogSlugRoute
  ItEventsFreeForeverRoute: typeof ItEventsFreeForeverRoute
  ItBlogIndexRoute: typeof ItBlogIndexRoute
}

const ItRouteChildren: ItRouteChildren = {
  ItIndexRoute: ItIndexRoute,
  ItBlogSlugRoute: ItBlogSlugRoute,
  ItEventsFreeForeverRoute: ItEventsFreeForeverRoute,
  ItBlogIndexRoute: ItBlogIndexRoute,
}

const ItRouteWithChildren = ItRoute._addFileChildren(ItRouteChildren)

interface PtRouteChildren {
  PtIndexRoute: typeof PtIndexRoute
  PtBlogSlugRoute: typeof PtBlogSlugRoute
  PtEventsFreeForeverRoute: typeof PtEventsFreeForeverRoute
  PtBlogIndexRoute: typeof PtBlogIndexRoute
}

const PtRouteChildren: PtRouteChildren = {
  PtIndexRoute: PtIndexRoute,
  PtBlogSlugRoute: PtBlogSlugRoute,
  PtEventsFreeForeverRoute: PtEventsFreeForeverRoute,
  PtBlogIndexRoute: PtBlogIndexRoute,
}

const PtRouteWithChildren = PtRoute._addFileChildren(PtRouteChildren)

interface RuRouteChildren {
  RuIndexRoute: typeof RuIndexRoute
  RuBlogSlugRoute: typeof RuBlogSlugRoute
  RuEventsFreeForeverRoute: typeof RuEventsFreeForeverRoute
  RuBlogIndexRoute: typeof RuBlogIndexRoute
}

const RuRouteChildren: RuRouteChildren = {
  RuIndexRoute: RuIndexRoute,
  RuBlogSlugRoute: RuBlogSlugRoute,
  RuEventsFreeForeverRoute: RuEventsFreeForeverRoute,
  RuBlogIndexRoute: RuBlogIndexRoute,
}

const RuRouteWithChildren = RuRoute._addFileChildren(RuRouteChildren)

interface ZhRouteChildren {
  ZhIndexRoute: typeof ZhIndexRoute
  ZhBlogSlugRoute: typeof ZhBlogSlugRoute
  ZhEventsFreeForeverRoute: typeof ZhEventsFreeForeverRoute
  ZhBlogIndexRoute: typeof ZhBlogIndexRoute
}

const ZhRouteChildren: ZhRouteChildren = {
  ZhIndexRoute: ZhIndexRoute,
  ZhBlogSlugRoute: ZhBlogSlugRoute,
  ZhEventsFreeForeverRoute: ZhEventsFreeForeverRoute,
  ZhBlogIndexRoute: ZhBlogIndexRoute,
}

const ZhRouteWithChildren = ZhRoute._addFileChildren(ZhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeRoute: DeRouteWithChildren,
  EsRoute: EsRouteWithChildren,
  HiRoute: HiRouteWithChildren,
  ItRoute: ItRouteWithChildren,
  PtRoute: PtRouteWithChildren,
  RuRoute: RuRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZhRoute: ZhRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  EventsFreeForeverRoute: EventsFreeForeverRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicCronGenerateArticlesRoute: ApiPublicCronGenerateArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
