/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuRouteImport } from './routes/ru'
import { Route as DeRouteImport } from './routes/de'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuBlogRouteImport } from './routes/ru.blog'
import { Route as ApiPublicCronGenerateArticlesRouteImport } from './routes/api/public/cron/generate-articles'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogRoute = RuBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => RuRoute,
} as any)
const ApiPublicCronGenerateArticlesRoute =
  ApiPublicCronGenerateArticlesRouteImport.update({
    id: '/api/public/cron/generate-articles',
    path: '/api/public/cron/generate-articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/de': typeof DeRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ru/blog': typeof RuBlogRoute
  '/api/public/cron/generate-articles': typeof ApiPublicCronGenerateArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/de': typeof DeRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ru/blog': typeof RuBlogRoute
  '/api/public/cron/generate-articles': typeof ApiPublicCronGenerateArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/de': typeof DeRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ru/blog': typeof RuBlogRoute
  '/api/public/cron/generate-articles': typeof ApiPublicCronGenerateArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/de'
    | '/ru'
    | '/sitemap.xml'
    | '/ru/blog'
    | '/api/public/cron/generate-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/de'
    | '/ru'
    | '/sitemap.xml'
    | '/ru/blog'
    | '/api/public/cron/generate-articles'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/de'
    | '/ru'
    | '/sitemap.xml'
    | '/ru/blog'
    | '/api/public/cron/generate-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  DeRoute: typeof DeRoute
  RuRoute: typeof RuRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCronGenerateArticlesRoute: typeof ApiPublicCronGenerateArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog': {
      id: '/ru/blog'
      path: '/blog'
      fullPath: '/ru/blog'
      preLoaderRoute: typeof RuBlogRouteImport
      parentRoute: typeof RuRoute
    }
    '/api/public/cron/generate-articles': {
      id: '/api/public/cron/generate-articles'
      path: '/api/public/cron/generate-articles'
      fullPath: '/api/public/cron/generate-articles'
      preLoaderRoute: typeof ApiPublicCronGenerateArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RuRouteChildren {
  RuBlogRoute: typeof RuBlogRoute
}

const RuRouteChildren: RuRouteChildren = {
  RuBlogRoute: RuBlogRoute,
}

const RuRouteWithChildren = RuRoute._addFileChildren(RuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  DeRoute: DeRoute,
  RuRoute: RuRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCronGenerateArticlesRoute: ApiPublicCronGenerateArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
